# New text only. Each string becomes a new, yellow-highlighted paragraph placed after existing text.

RELATED_ART = [
 "Related art concerning autonomous agents and their supporting infrastructure is also known. Agent frameworks and tool protocols, including the Model Context Protocol, allow a language-model agent to call external tools, read files, and act on a user’s behalf. Document-ingestion pipelines extract text from files of many formats for indexing or for supply to a model. Blockchain notarization services record the hash of a document on a public ledger, and non-fungible tokens record ownership of a digital item. Deception technologies — honeypots, honeytokens, and canary credentials — are used to detect intruders, and append-only logs and Merkle-tree structures are used to make records tamper-evident. Streaming systems deliver media over TCP/IP in formats such as HLS, MPEG-DASH, and RTMP.",
 "These systems leave recurring gaps when applied to knowledge systems used by AI agents. An agent that reads a file can be redirected by instructions hidden in that file (prompt injection); an agent connected through a tool protocol commonly receives whatever capability the tool exposes; an intruder who obtains an agent’s identity can impersonate it; and security logs held on the attacked host can be altered after the fact. A notarized hash attests that a document existed but not its lineage, revocation, or licence status, and conventional media transport carries no provenance for the content it delivers. What is needed is ingestion that treats every file as data and never as instruction; certification of knowledge that any third party can verify, with lineage and revocation; protection that detects, contains, and records hostile agent behaviour without exposing production data; security records whose alteration is detectable against copies the host cannot change; agent connections that confer no capability beyond a declared allow-list; and transport that carries provenance with both records and media.",
]

SUMMARY_HEAD = "H.  Recent Feature Additions"
SUMMARY_INTRO = "Recent developments extend QueryBook for operation with and among AI agents, each operating under the Prime Directive and expressed over the same Fact Unit, UFCS, and FQL foundation layer:"
SUMMARY_ITEMS = [
 "   a. Open Claw ingestion of artifacts of any format — documents, spreadsheets, presentations, page-description files, archives, messages, images, audio, and video — identified by content, divided into located segments, and converted into Fact Units, every artifact being treated as data and never as instruction (FIG. 19).",
 "   b. On-chain certification, in which a sealed Fact Unit, book, or response may optionally be certified as a non-fungible token on a public blockchain carrying its content hash, lineage, and revocation state, verifiable by any party without access to QueryBook (FIG. 20).",
 "   c. An agent protection and deception layer in which every agent call passes an Agent Gateway and is screened by honeycode, honeytokens, tripwires, honeypot agents, an AI-aware firewall, and anomaly detection, a hostile caller being isolated into a synthetic decoy environment with no path to production data (FIG. 21).",
 "   d. A tamper-evident security record of hash-chained entries sealed by write-once, signed Merkle checkpoints, mirrored and optionally anchored on a public blockchain, and verified by recomputation from content (FIG. 22).",
 "   e. Agent interoperability through a Model Context Protocol tool server and an OpenClaw skill, every external agent call passing the Agent Gateway under that agent’s allow-list (FIG. 23).",
 "   f. A framed hybrid transport extending the QueryBook-enhanced TCP/IP protocol, carrying Fact Units and media in checksummed, optionally signed frames on separate priority lanes and rebuilding media into standard HLS, MPEG-DASH, or RTMP streams (FIG. 24).",
]
SUMMARY_CLOSE = "These additions are implemented in the QueryBook prototype and are described in the Detailed Description of the Invention."

BRIEF = [
 (19, "is a block diagram of Open Claw ingestion, showing content-based format detection, archive bounds, the Artifact Segmenter, the instruction-like content screen, the OpenClaw Interpreter, and the admission of artifact-description, structured, passage, and flagged untrusted records to the Fact Unit store under a provenance seal."),
 (20, "is a block diagram of on-chain certification, showing a QueryBook object and its local provenance seal, the content hash and on-chain metadata, the in-system transaction signer and network guard, the certificate contract on a public blockchain, the independent verifier, and the licence check."),
 (21, "is a block diagram of the agent protection and deception layer, showing the HTTP gate, the isolation register, the Agent Gateway, the deception check with honeycode, honeytokens, tripwires, and honeypot agents, the AI-aware firewall and anomaly detector, the security event bus, the decoy environment, the engagement recorder, and operator-only release."),
 (22, "is a block diagram of the tamper-evident security record, showing append-only entries, the hash chain, write-once signed Merkle checkpoints, a mirror on a second device, a blockchain anchor, the recompute-from-content verifier with inclusion proofs, and the assurance report."),
 (23, "is a block diagram of agent interoperability, showing an external AI agent and its skill definition, the Model Context Protocol tool server, the tool-to-command mapping, the Agent Gateway with the agent’s allow-list, grounded handlers, and isolation upon a reserved command."),
 (24, "is a block diagram of the framed hybrid transport, extending FIG. 17, showing per-type compression, the frame with its header, metadata, payload, CRC32 checksum, and optional signature, the control, normal, and bulk lanes, the receiver, package rebuild with manifest check, and record verification into the Fact Unit store."),
]
DRAWING_NOTE = "[Drafting note: line-art drawings for FIG. 19–24 are provided in the accompanying drawings PDF for FIG. 19–24 and are prepared to the same standard; reference numerals 5000–5550 used in FIG. 19–24 are identified in the Detailed Description.]"

SYS_HEAD = "Recent Feature Additions"
SYS_INTRO = "QueryBook has been further extended for a world in which AI agents read files, call tools, and query other systems on people’s behalf. The additions keep the same rule as the rest of the system — nothing enters the answer path unverified, everything is recorded, and the record itself cannot be quietly altered:"
SYS_ITEMS = [
 "1. Any-format ingestion (Open Claw). Files of any kind can be submitted. QueryBook identifies each file by its content, divides it into addressable pieces, and turns those pieces into Fact Units. Text hidden in a file to give orders to an AI is flagged and stored as untrusted, below the level at which it could affect an answer.",
 "2. Certificates anyone can check. A Fact Unit, a book, or an answer can optionally be certified on a public blockchain as a non-fungible token that records its content hash, what it derives from, and whether it has been revoked. Anyone holding the item can confirm it without access to QueryBook.",
 "3. Protection for QueryBook’s agents and for agents that use it. Every agent call passes one gateway. Traps that no legitimate caller would touch — reserved commands, fake credentials, reserved paths, and decoy agents — reveal hostile intent; a hostile caller is moved into a convincing decoy that has no route to real data, and everything it does is recorded.",
 "4. A security log that cannot be quietly changed. Security decisions are chained together and sealed in write-once checkpoints that can be copied to a second device and anchored on a blockchain, so any later alteration is detectable.",
 "5. Connection to outside AI agents. Agents such as OpenClaw connect through a standard Model Context Protocol tool server and receive only the tools on their allow-list, so connecting an agent never grants it more than QueryBook permits.",
 "6. Faster, provenance-carrying transport. Fact Units and media travel in checked and optionally signed frames on separate priority lanes over ordinary TCP/IP, so a question is never stuck behind a large file, and media can be rebuilt into standard streaming formats on arrival.",
]

CORE_HEAD = "Recent Enhancements: Ingestion, Certification, Agent Protection, Security Record, Interoperability, and Transport"
CORE_PARAS = [
 ("Open Claw ingestion (FIG. 19). ", "An artifact of any format (5000) is identified by content-based format detection (5010) from its leading bytes and structure rather than its file name, and archive bounds on depth, member count, size, and expansion ratio (5070) are enforced before expansion. The Artifact Segmenter (5020) divides the artifact into addressable segments carrying source locators — page, sheet and cell, slide, archive member, or time range — and an executable component is described but never executed (5025). An instruction-like content screen (5040) flags text addressed to an AI system rather than a human reader, including hidden text. The OpenClaw Interpreter (5050) converts segments into artifact-description records (5051), structured records (5052), and passages with extracted claims at reduced confidence (5053); a flagged segment becomes an untrusted record whose trust is set below the answer threshold (5060). Records are admitted to the Fact Unit store (5095) under a provenance seal (5090), and a path requested by an external agent is confined to a designated inbox (5080)."),
 ("On-chain certification (FIG. 20). ", "A QueryBook object (5110) already carries a local provenance seal (5100). Where an operator elects it, the object’s content hash and metadata (5120) are recorded on a public blockchain (5170) by a certificate contract (5160) of the ERC-721 type that permits one token per content hash, records predecessor and successor lineage, and supports revocation with a stated reason. Transactions are signed by an in-system transaction signer (5140) that checks its primitives against published test vectors at start-up, and a network guard (5150) restricts certification to test networks unless a money-bearing network is expressly elected. An independent verifier (5180) recomputes the content hash and reports whether a certificate exists, who holds it, and whether it is revoked or superseded; a licence check (5190) may grant a use to the holder of a current, unrevoked token. A certificate proves that a hash was certified, not that the content is true. The blockchain is a public network operated by others, the system acting as a client of it; the cryptographic integrity chain within the Fact Graph continues to require no distributed ledger or token."),
 ("Agent protection and deception (FIG. 21). ", "Every call from a caller (5200) — an internal agent, an external agent, a tool server, or an HTTP client — passes an HTTP gate carrying honeypages and canary tokens (5210) and an isolation register (5260), and then the Agent Gateway (5220), which authenticates the caller by a keyed identity token within a bounded replay window and applies its role and per-agent allow-list, complementing the AI Agent Passport System. A deception check (5230) comprises honeycode (5231), reserved commands never listed to any caller; honeytokens (5232), canary credentials no legitimate process uses; tripwires (5233), reserved paths and acts such as a request to purge the security record; and honeypot agents (5234). An AI-aware firewall (5240) detects injection, secret-reveal, and role or tag tricks, and an anomaly detector (5241) detects enumeration and timing patterns. A trigger posted to the security event bus (5250) isolates the caller into a decoy environment (5270) that returns production-shaped, synthetic responses with no path to production data, while an engagement recorder (5280) records the session. Isolation is keyed to the actual connection, so a caller impersonating a legitimate agent isolates only itself; release (5261) is available only to the operator locally, through no network interface; and every decision is written to the security record (5295). In the embodiment reduced to practice the layer observes, contains, and deceives within the system’s own boundary."),
 ("Tamper-evident security record (FIG. 22). ", "Each security decision (5300) is written as an append-only entry (5310) recording agent, caller, session, command, a parameter hash, the decision, and flags, with no update or delete interface. Each entry hash commits to its predecessor (5320). Every N entries and on demand, a Merkle checkpoint (5330) is created exclusively, never overwritten, signed under the deployment key, and chained to the previous checkpoint; it may be copied to a mirror on a second device (5340) and its root anchored on a public blockchain through the certificate contract of FIG. 20 (5350). A verifier (5360) recomputes every entry and root from content, never trusting a stored hash, and produces a Merkle inclusion proof per entry, and an assurance report (5370) states which protections a record possesses. The record extends, and does not replace, the post-quantum provenance ledger."),
 ("Agent interoperability (FIG. 23). ", "An external AI agent (5400), for example an OpenClaw agent guided by a skill definition (5410) instructing it to cite, to report UNKNOWN, to treat ingested content as data, and to stop on isolation, reaches QueryBook through a Model Context Protocol tool server (5420) exposing a fixed set of tools — query, verify, understand, ingest, preview, ledger, certificate, and status — and never listing reserved honeycode. Each tool is mapped (5430) to a command under the agent’s registered identity and checked by the Agent Gateway (5440) against the agent’s allow-list (5450); permitted calls reach grounded handlers (5460), and an agent invoking a reserved command is presumed subverted and isolated (5470)."),
 ("Framed hybrid transport (FIG. 24). ", "Extending the protocol of FIG. 17, a producer node (5500) applies per-type compression (5510) — record batches by a dictionary primed with record field names, media by a standard codec left unaltered — and packs the result into frames (5520) comprising a 32-byte header (5521), metadata (5522), payload (5523), a CRC32 checksum (5524), and an optional signature (5525). Frames travel on a control lane (5530), a normal lane (5531), and a bulk lane (5532), each with its own connection, rate limit, and receipt window, so a bulk transfer cannot hold a control message or a live stream behind it. The receiver (5541) drops a frame failing plausibility, checksum, or signature checks and resynchronizes at the next marker; media is rebuilt into HLS, MPEG-DASH, or RTMP packages with a manifest check (5543), and records pass verification into the Fact Unit store (5550). The transport neither enlarges nor alters a compressed asset."),
 ("Implementation status. ", "The features of FIG. 19–24 are implemented in QueryBook prototype version 9.64 and exercised by automated self-tests, including a sandboxed attack trial against the gateway and decoy and certificate minting, lineage, revocation, and verification on a local test chain; deterministic record-grounded colorization has additionally been implemented in a laboratory prototype at 1K, 4K, and 16K frame sizes."),
]

ARCH_HEAD = "Agent-era extensions within the domain organization"
ARCH_PARAS = [
 "The recent extensions occupy existing domains and add no authority outside them. Open Claw ingestion is a pathway of the ingestion and sensory-intake domain (102): an artifact of any format is converted into candidate records under the same admission rules as any other modality, content of the artifact is never executed, and a segment flagged as instruction-like enters only as an untrusted record below the answer threshold.",
 "The Agent Gateway, deception check, firewall, isolation register, and decoy environment operate at the boundary governed by the governance domain (112) and the transfer matrix: every agent call is a boundary crossing that is evaluated and recorded, a denied or isolated caller is routed to a decoy that has no transfer path to the substrate, and release from isolation is reserved to the operator locally. The tamper-evident security record and optional on-chain certificates extend the provenance ledger (106) outward, giving third parties independent means to verify security decisions and certified records without access to the system.",
 "External agents connected through the Model Context Protocol tool server act as callers of the system and never as domains of it: each tool maps to a declared command under the agent’s allow-list, so connection confers no capability beyond that list. The framed hybrid transport carries records and media between deployments in every deployment mode without changing which domain owns any decision.",
]
