# Registry v68 additions: QueryBook-side support for external agent-wrapper services (such as Verified Agent Transport,
# which is registered separately). Same tuple layout as v66_data.NEW / ALGOS. VAT's own features are NOT listed here.
SPEC = "Specified"
C = "Support spec 2026-10-09"
NEW = [
 ("Claim Verification Endpoint", "Retrieval & Response", [22, 6], "System", "Wrapper service",
  "Accept a batch of candidate Fact Units or fingerprints from an authorized external service and return, for each, verified, contradicted or unknown with the citing FUID and its trust.",
  "Read-only: the endpoint never writes to the Fact Unit store, and unknown is never reported as false.",
  '=IF(0.78>=0.5,"verified","unknown")', SPEC, "qb_api, ufcs_store (planned)"),
 ("Contradiction Query Template", "Retrieval & Response", [6, 7], "System", "Wrapper service",
  "A canned FQL query: MATCH the claim's subject and predicate WHERE trust is at least the minimum, EXCLUDE the claim's object; the same triple with opposite polarity also counts as a contradiction.",
  "A rival contradicts only if its trust exceeds the trust of the claim's source.",
  '=IF(AND("Paris"<>"Lyon",0.9>0.4),"contradicted","no contradiction")', SPEC, "FQL engine (planned)"),
 ("Fingerprint-Only Verification Mode", "Access, Rights & Retention", [21], "System", "Wrapper service",
  "Answer verification requests from fingerprints, and for contradiction checks from canonical subject and predicate identifiers alone.",
  "Claim text and objects are never required and never stored by the endpoint in this mode.", None, SPEC, "qb_api, ufcs_store (planned)"),
 ("External Triple Extraction Interface", "Ingestion & Sensory Intake", [2, 6], "System", "Wrapper service",
  "Expose query understanding to authorized callers: a sentence in, subject / predicate / object / polarity with canonical identifiers and semantic fingerprint out.",
  "A sentence that cannot be converted is returned as unconverted, never guessed.", None, SPEC, "qb_query (planned)"),
 ("Assertion-Type Label (Fact / Opinion / Plan / Prediction)", "Knowledge Substrate", [2], "System", "Wrapper service",
  "Add an assertion-type label to candidate records so that opinions, plans and predictions can be carried and labelled alongside facts.",
  "Only a record labelled fact can be certified or used as a verification citation.",
  '=IF("opinion"="fact","Eligible for certification","Label only - never certified")', SPEC, "ufcs_store (planned)"),
 ("Signed Verdict Record and Published Verifier Key", "Platform Governance & Evolution", [53, 51], "System", "Wrapper service / Auditor",
  "Sign every verification response with an Ed25519 key held by the endpoint; publish the public key; record key rotation in the security log.",
  "An unsigned or wrongly signed verdict is invalid; retired keys remain published for verifying old verdicts.", None, SPEC, "qb_api, qb_seclog (planned)"),
 ("Frame Message-Type Extension Range", "External Integration & Analysis", [55], "System", "Wrapper service",
  "Reserve message types 16–31 of the UFCS-FQL/1 header for registered extensions; types 0–2 keep their meanings.",
  "A frame with an unregistered type is dropped and recorded, never forwarded.",
  '=IF(AND(22>=16,22<=31),"Extension type","Core or invalid type")', SPEC, "ufcs-transport-lab (planned)"),
 ("Frame Extension Flag and Reserved-Field Profile", "External Integration & Analysis", [55], "System", "Wrapper service",
  "Reserve flag 0x0040 for extension use (verified hop) and define the 32-bit reserved header field as a 16-bit session number and a 16-bit hop count for extensions.",
  "Core frames leave both at zero; the header layout and length are unchanged.",
  '=MOD(70000,65536)&" session / "&INT(70000/65536)&" hop"', SPEC, "ufcs-transport-lab (planned)"),
 ("Python UFCS-FQL/1 Frame Codec", "External Integration & Analysis", [55], "System", "Developer",
  "A standard-library Python encoder and decoder for UFCS-FQL/1 frames, including CRC32 and optional Ed25519 signature.",
  "Round trip is byte-identical with frames produced by the PHP transport laboratory.", None, SPEC, "qb_frames (planned)"),
 ("QUIC Stream Binding for Priority Lanes", "External Integration & Analysis", [55], "System", "Operator",
  "Carry the control, normal and bulk lanes as independent QUIC streams over one connection, falling back automatically to three TLS-on-TCP connections when UDP is blocked.",
  "A stalled bulk stream never delays the control lane; QUIC support is an optional dependency.", None, SPEC, "ufcs-transport-lab, qb_frames (planned)"),
 ("Fingerprint Set Reconciliation (Have / Want)", "Knowledge Substrate", [21, 55], "System", "Peer node",
  "Before bulk transfer, peers exchange the fingerprints they hold and the ones they need; lists over 4,096 entries travel as a Bloom filter (false-positive rate ≤ 1e-6) followed by an exact list.",
  "Only missing Fact Units are sent; every received record is re-fingerprinted from content before admission.",
  '=IF(5000>4096,"Bloom filter","Exact list")', SPEC, "ufcs_store, qb_frames (planned)"),
 ("External Service Append to Security Log", "Platform Governance & Evolution", [53], "System", "Wrapper service",
  "Allow a registered service identity to append its own event types to the hash-chained security log under the existing chaining and checkpoint rules.",
  "Appends are attributed to the service identity; no service can alter or delete an entry.", None, SPEC, "qb_seclog (planned)"),
 ("Session-Range Merkle Root", "Platform Governance & Evolution", [53], "System", "Auditor",
  "Compute a Merkle root and inclusion proofs over the security-log entries carrying a given session identifier.",
  "Recomputing the root from the same entries always gives the same value; any altered entry changes it.",
  '=IF(2^CEILING(LOG(212,2),1)>=212,"Tree leaves: "&2^CEILING(LOG(212,2),1),"")', SPEC, "qb_seclog (planned)"),
 ("Third-Party Session Certificate Type", "Commerce & Entitlement Tokens", [51], "System", "Auditor",
  "A certificate kind for sessions certified by an external service — counts, coverage and a session Merkle root — sealed as a Fact Unit and checkable by the independent certificate verifier.",
  "The certificate states what was checked and found; it never asserts that a party is honest or that content is true.", None, SPEC, "qb_nft (planned)"),
 ("Principal Evidence Pair (Agent Reputation Store)", "Inference, Prediction & Calibration", [19, 52], "System", "Operator",
  "Keep a Beta evidence pair per agent identity, updated from signed verdicts; report α / (α + β) with a credible interval.",
  "A low score only proposes restriction; restriction requires a recorded operator decision (Default-on-Deny).",
  '=ROUND((41+1)/((41+1)+(2+1)),3)', SPEC, "qb_shield (planned)"),
 ("Signed Policy Bundle Export", "Access, Rights & Retention", [52], "System", "Operator",
  "Export Agent Gateway allow-lists, honeytokens and verification tiers as signed, versioned, pull-only bundles for external enforcement points.",
  "An enforcement point rejects any bundle that is unsigned or older than the one it holds.",
  '=IF(AND(TRUE,17>=16),"Accept bundle v17","Reject bundle")', SPEC, "qb_shield (planned)"),
 ("MCP Pre-Call and Post-Call Hooks", "External Integration & Analysis", [54], "System", "Wrapper service",
  "Expose interception points in the MCP tool server so a registered wrapper sees each tool call before execution and each result before delivery.",
  "Hooks may observe, label or refuse; they cannot alter a tool's result record.", None, SPEC, "qb_mcp (planned)"),
 ("Tool Result Record Hash", "External Integration & Analysis", [54, 53], "System", "Auditor",
  "Attach to every MCP tool response a SHA-256 hash of the tool's own result record and log it in the security log.",
  "An agent's later report of the result can be compared with the hash; a mismatch is recorded.", None, SPEC, "qb_mcp, qb_seclog (planned)"),
 ("Wrapper Service Registration", "Access, Rights & Retention", [52], "System", "Operator",
  "Register an external wrapper service with identity, public key and scope through the Agent Gateway, granting read-only verification rights and log-append rights only.",
  "A wrapper service can never write to the Fact Unit store or act as a domain of the system.", None, SPEC, "qb_shield (planned)"),
]
ALGOS = [
 ("ALG-14", "Claim verification endpoint", "Claim Verification Endpoint; Contradiction Query Template; Signed Verdict Record and Published Verifier Key", [22, 6, 7],
  "Candidate Fact Units or fingerprints; minimum trust",
  "1. If the fingerprint is certified at or above minimum trust: verified, cite it. 2. Otherwise run the contradiction template (same subject and predicate, other object, or opposite polarity, trust ≥ minimum); a rival above the source's trust gives contradicted, citing the strongest. 3. Otherwise unknown. 4. Sign each response with the endpoint key.",
  "Signed verdict records", "Yes", "qb_api, ufcs_store (planned)"),
 ("ALG-15", "Fingerprint set reconciliation", "Fingerprint Set Reconciliation (Have / Want)", [21, 55], "Fingerprint sets of two peers",
  "1. Sender lists held fingerprints; above 4,096 it sends a Bloom filter sized for a false-positive rate ≤ 1e-6. 2. Receiver answers with the fingerprints it lacks (exact list for Bloom hits). 3. Sender transmits only those records. 4. Receiver re-fingerprints each record from content before admission.",
  "Minimal record transfer", "Yes", "ufcs_store, qb_frames (planned)"),
 ("ALG-16", "Session-range Merkle root and certificate check", "Session-Range Merkle Root; Third-Party Session Certificate Type", [53, 51], "Security-log entries for a session; certificate",
  "1. Select entries with the session identifier in sequence order. 2. Hash each; build the Merkle tree; take the root. 3. Compare with the certificate's root and any anchor; verify the certificate signature. 4. Report match or the first mismatching entry via inclusion proofs.",
  "Root; verification report", "Yes", "qb_seclog, qb_nft (planned)"),
 ("ALG-17", "Principal evidence pair update", "Principal Evidence Pair (Agent Reputation Store)", [19, 52], "Signed verdicts per agent",
  "1. α = 1 + weighted verified count; β = 1 + weighted contradicted count; unknown leaves both unchanged. 2. Score = α / (α + β); credible interval from Beta(α, β). 3. Below threshold, raise an operator proposal; apply only on a recorded decision.",
  "Score, interval, proposal", "Yes", "qb_shield (planned)"),
 ("ALG-18", "Signed policy bundle export and acceptance", "Signed Policy Bundle Export; Wrapper Service Registration", [52], "Gateway policy; bundle version; signing key",
  "1. Serialize allow-lists, honeytokens and tiers canonically with a version number. 2. Sign. 3. Enforcement point pulls, verifies the signature and accepts only a version greater than or equal to the one it holds. 4. Log acceptance or rejection.",
  "Accepted bundle or logged rejection", "Yes", "qb_shield (planned)"),
 ("ALG-19", "Tool-call interception and result hashing", "MCP Pre-Call and Post-Call Hooks; Tool Result Record Hash", [54, 53], "Tool call; tool result record",
  "1. Pre-call hook receives the call and may observe, label or refuse. 2. Tool executes. 3. Hash the tool's own result record (SHA-256) and log it. 4. Post-call hook receives the result and the hash; the result record itself is immutable.",
  "Result with record hash; log entries", "Yes", "qb_mcp, qb_seclog (planned)"),
]
