<?php

declare(strict_types=1);

require __DIR__ . '/_harness.php';

// --- Colour knowledge is ordinary UFCS --------------------------------------
$feed = Ufcs::decodeBatch((string) file_get_contents(ColorKnowledge::FILE));
check(count($feed) === count(ColorKnowledge::BUILTIN), 'shipped colour feed matches the built-in knowledge');
check(array_filter($feed, fn ($r) => Ufcs::validate($r) !== null) === [], 'every colour fact re-validates its semantic fingerprint');
check(ColorKnowledge::records(ColorKnowledge::BUILTIN) === $feed, 'feed is regenerated byte-for-byte from the built-in rows');
$k = new ColorKnowledge();
check($k->colorOf('sky_clear')[0] === '#627A9D', 'FQL resolves a material colour');
check(in_array('sand', $k->materialsFor('beach'), true), 'scene prior: a beach implies sand');
check($k->gradeFor('era:1950s')['saturation'] === 1.2, 'historical prior: 1950s grade');
$k->addFacts(ColorKnowledge::records([['sky_clear', 'has_typical_color', '#4A6FA5', 'user']]));
check($k->colorOf('sky_clear')[0] === '#4A6FA5', 'a higher-trust fact supplied with the job wins (RANK BY trust)');
check(abs(Colorizer::chroma('#808080')[0]) < 0.01 && abs(Colorizer::chroma('#808080')[1]) < 0.01, 'gray has no chroma');
check(abs(Colorizer::lab(255, 255, 255)[0] - 100) < 0.01, 'Lab of white is L*=100');
check(Colorizer::parseScene('setting=lake, beach;time=golden hour;with=people') === [['setting', 'lake'], ['setting', 'beach'], ['time_of_day', 'golden_hour'], ['contains', 'people']], 'scene shorthand parses into facts');

if (MediaCodec::ffmpeg() === '') {
    echo "  (skip rendering: ffmpeg not installed)\n";
    done('colorization-contract');
    exit(0);
}

$work = sys_get_temp_dir() . '/ufcs-color-test-' . bin2hex(random_bytes(4));
mkdir($work);
DemoScenes::landscape("$work/scene.png");
MediaCodec::exec([MediaCodec::ffmpeg(), '-hide_banner', '-loglevel', 'error', '-y', '-i', "$work/scene.png", '-vf', 'format=gray', "$work/bw.png"]);

// --- A still: 1K / 4K / 16K, scored against the true colours ----------------
$o = ['scene' => 'setting=lake,beach;time=midday', 'regions' => ['0.66,0.28,0.82,0.55=stone'], 'targets' => ['1k', '4k', '16k'], 'out_dir' => "$work/a", 'evaluate' => true];
$m = (new Colorizer())->run("$work/scene.png", $o);
$dims = array_map(fn ($x) => [$x['width'], $x['height']], $m['outputs']);
check($dims === ['1k' => [1024, 576], '4k' => [3840, 2160], '16k' => [15360, 8640]], '1K, 4K and 16K at the exact target sizes');
foreach ($m['outputs'] as $t => $x) {
    check(is_file($x['file']) && $x['bytes'] > 0, "$t output written");
    $info = MediaCodec::probe($x['file']);
    check($info['width'] === $x['width'] && $info['height'] === $x['height'], "$t file really is {$x['width']}×{$x['height']}");
    check($x['consistency_psnr_db'] >= 40, "$t luminance stays consistent with the source ({$x['consistency_psnr_db']} dB ≥ 40)");
}
check($m['evaluation']['improvement_pct'] >= 60, 'colorized is ≥ 60% closer to the true colour than gray (' . $m['evaluation']['improvement_pct'] . '%)');
check(array_column($m['agents'], 'agent') === array_keys(Colorizer::AGENTS), 'all eight declared agents ran, in order (F76)');
check(str_contains($m['marking'], 'reconstructed') && is_file($m['manifest_file']), 'colour is marked as reconstructed and the manifest is written (F225)');
foreach ($m['regions'] as $cls => $r) {
    $p = $m['palette'][$cls];
    check($r['mean_confidence'] <= $p['trust'] + 1e-9, "$cls confidence never exceeds its fact's trust (F224)");
}

// --- Determinism (F22) -----------------------------------------------------
$m2 = (new Colorizer())->run("$work/scene.png", ['targets' => ['1k'], 'out_dir' => "$work/b"] + $o);
check($m2['determinism']['chroma_sha256'] === $m['determinism']['chroma_sha256'], 'identical inputs give identical colour');
check($m2['outputs']['1k']['sha256'] === $m['outputs']['1k']['sha256'], 'identical inputs give a byte-identical 1K file');

// --- Withhold rather than fabricate (F182) ----------------------------------
$lake = (new Colorizer())->run("$work/bw.png", ['scene' => 'setting=lake', 'targets' => ['1k'], 'out_dir' => "$work/c", 'evaluate' => true]);
check(!isset($lake['regions']['skin']) || $lake['regions']['skin']['withheld_pct'] === 100.0, 'with no people in the facts, anything that looks like skin stays gray');
check(isset($lake['evaluation']['skipped']), 'a black-and-white source is not scored against itself');

// --- Facts change the picture -----------------------------------------------
$fact = (new Colorizer())->run("$work/bw.png", ['scene' => 'setting=lake,beach;time=golden_hour;era=1950s', 'facts' => ['Old Mill | has_color | #B03A2E'],
    'regions' => ['0.66,0.28,0.82,0.55=Old Mill'], 'targets' => ['1k'], 'out_dir' => "$work/d"]);
check(($fact['palette']['Old Mill']['hex'] ?? '') === '#B03A2E' && $fact['regions']['Old Mill']['mean_confidence'] > 0.8, 'a known colour supplied as a fact paints its region');
check($fact['palette']['sky']['subject'] === 'sky_dusk', 'golden-hour lighting switches the sky to its dusk colour');
check(abs($fact['grade']['saturation'] - 1.32) < 0.001 && abs($fact['grade']['warmth'] - 0.11) < 0.001, 'era and lighting grades combine (1.2 × 1.1, 0.03 + 0.08)');
check(in_array('FIND fact WHERE subject = "Old Mill" AND predicate IN [has_color, has_typical_color] RANK BY trust LIMIT 1', $fact['fql'], true), 'the FQL behind each colour is recorded');

// --- Video: 1K/4K files and a 16K frame sequence ----------------------------
DemoScenes::landscapeClip("$work/clip.mp4", 1.0, 640, 360);
$v = (new Colorizer())->run("$work/clip.mp4", ['scene' => 'setting=lake,beach', 'targets' => ['1k', '4k', '16k'], 'out_dir' => "$work/v", 'max_16k_frames' => 2]);
check($v['input']['kind'] === 'video' && $v['input']['frames'] === 30, 'clip ingested as 30 frames');
check($v['outputs']['1k']['frames'] === 30 && $v['outputs']['4k']['format'] === 'MP4' && $v['outputs']['16k']['frames'] === 2, 'video: 1K and 4K files, 16K as a capped frame sequence');
$meta = MediaCodec::exec([dirname(MediaCodec::ffmpeg()) . '/ffprobe', '-v', 'error', '-show_entries', 'format_tags=comment', '-of', 'csv=p=0', $v['outputs']['4k']['file']]);
check(str_contains($meta['stdout'], 'colour reconstructed'), 'the 4K video carries the reconstruction marking in its metadata');
check($v['outputs']['16k']['consistency_psnr_db'] >= 40, '16K frames stay consistent with the source');

StreamPackager::removeDir($work);
done('colorization-contract');
