# New QueryBook-first content for the rebalanced provisional (rev. October 8, 2026 (B)).
# All numbers here are in the NEW numbering. Paragraph labels [Bnn]/[Ann] are placeholders
# resolved to sequential [00nn] numbers by build_rebal.py.

def P(label, body):
    return f'<p class="pp add"><span class="n">[{label}]</span> {body}</p>\n'

TITLE = "QueryBook — A Deterministic, Provenance-Tracked Federated Knowledge and Query System and Method"

REV = ("; rev. October 8, 2026 (B) — rebalanced as a QueryBook-system application: QueryBook core platform described first "
       "(Part A, FIG. 1–22, new claims 1–20) with its language, identity, media and agent subsystems presented in proportion; "
       "figures, reference numerals, paragraphs, sections and claims renumbered. Figure, section and claim numbers in this "
       "revision history refer to the present numbering")

NOTE = ('<p class="add" style="font-size:12px;color:var(--muted);font-family:var(--sans)"><b>Note on this draft.</b> '
 'This provisional specification is a single, consolidated QueryBook application directed to the QueryBook system as a whole. '
 'Part A describes the QueryBook core platform — the Fact Unit, the Universal Federated Connectivity System (UFCS) substrate, '
 'the Federated Query Language (FQL), certification, verification, grounded response generation, federation, erasure, the '
 'Prime Directive, governed agents, security and deployment (FIG. 1–FIG. 22). Parts B, C and D describe subsystems and '
 'embodiments built on that core: the integral language and speech subsystem (the Language Expression Layer, LEL; '
 'FIG. 23–FIG. 32), the identity, audit, interpretation and lecture embodiments (FIG. 33–FIG. 40), and further embodiments '
 'including media handling and the agent-era extensions (FIG. 41–FIG. 55). Each subsystem inherits the core’s determinism, '
 'provenance and no-fabrication guarantees. Refinements from an internal engineering audit are marked '
 '<span class="fix">audit</span>. Drawings are draft, to be finalized to USPTO drawing standards (37 CFR 1.84) by a patent '
 'draftsperson. Claims must be reviewed, and a prior-art search conducted, by qualified patent counsel before filing.</p>')

DRAWINGS_INTRO = ('<p class="add" style="font-size:12px;color:#5a554b;font-family:Helvetica,Arial,sans-serif">Formal patent drawings — '
 'black line art, forming <b>one QueryBook figure set</b>, ordered from the core outward: FIG. 1–FIG. 22 depict the QueryBook '
 'core platform (Part A); FIG. 23–FIG. 32 depict the integral language and speech subsystem (Part B); FIG. 33–FIG. 40 depict the '
 'identity, integrity-audit, interpretation and lecture embodiments (Part C); and FIG. 41–FIG. 55 depict further embodiments, '
 'applications, media handling and the agent-era extensions (Part D). Each figure is on its own sheet and every element is '
 'identified by a reference numeral used consistently in the Brief Description of the Drawings, the Reference Numerals key, and '
 'the Detailed Description; the core-platform figures use the 6100–8210 numeral series. Figures are draft; counsel/draftsperson '
 'to finalize to USPTO drawing standards (37 CFR 1.84) before filing.</p>\n')

GROUPS = [  # (first fig, heading)
 (1, "Part A — QueryBook core platform (FIG. 1–FIG. 22)"),
 (23, "Part B — Language and speech subsystem (FIG. 23–FIG. 32)"),
 (33, "Part C — Identity, integrity-audit, interpretation and lecture embodiments (FIG. 33–FIG. 40)"),
 (41, "Part D — Further embodiments, applications, media and agent-era extensions (FIG. 41–FIG. 55)"),
]

FIELD = """<h2>Field of the Invention</h2>
  <p class="add">The present invention relates to knowledge systems and, more particularly, to QueryBook: a deterministic, provenance-tracked, federated knowledge and query system in which knowledge is held as atomic, content-addressed Fact Units, each carrying its own evidence-based confidence, certification, provenance and safety classification; in which queries are executed in a Federated Query Language that evaluates structure and trust together over a Universal Federated Connectivity System substrate; in which every answer is composed only from verified records, cited, and refused when unknown; and in which every output and action is governed by a Prime Directive operating as a Domain-0 safety plane.</p>
  <p class="add">The invention further relates to subsystems and embodiments built on that core and sharing its guarantees: an integral language and speech subsystem (the Language Expression Layer) by which input in any supported language resolves to the same query representation and results are rendered as language or speech; voiceprint identity, integrity-audit, paralinguistic interpretation and lecture-ingestion embodiments; edition packaging and store continuity; meaning-based handling of pictures, sound and video; and agent-era extensions for arbitrary-artifact ingestion, on-chain certification, agent protection, tamper-evident security records, agent interoperability and framed transport.</p>
"""

BACKGROUND = "<h2>Background of the Invention</h2>\n" + "".join([
 P("B01", "Information systems answer questions in two principal ways. Retrieval systems — databases, document stores and search engines — return stored rows or documents, but do not establish which specific assertion supports an answer or how reliable that assertion is. Generative language models produce fluent text by statistical next-token prediction and have no native mechanism to distinguish a well-supported answer from a plausible one, because both are produced by the same generative process. Retrieval-augmented generation attaches retrieved documents to a generative model, but the generated text remains unconstrained by them."),
 P("B02", "The consequences are well known. A fabricated statement is indistinguishable in form from a supported one; a citation names a source without a verifiable binding between the sentence and the evidence; confidence, where reported at all, is a single number that cannot distinguish strong evidence from thin evidence or one source repeated from many independent sources; contradictions between sources go undetected; and a correction made in one place does not propagate to the answers that relied on the corrected material."),
 P("B03", "Knowledge stored as text is also entangled with the language in which it was written. A corpus in six languages is in effect six corpora: a query must be translated to reach material in another language, a correction must be made once per language, and an error introduced in translation is indistinguishable afterwards from an error in the source."),
 P("B04", "Sharing knowledge across organizational boundaries presents further problems. A record received from another system is typically trusted or rejected wholesale rather than re-validated against its certification; removing a single record from an immutable or append-only store conflicts with the store’s integrity guarantees; and safety and access rules are commonly applied as filters around a result, which a code path can bypass, rather than carried within each record. As automated agents begin to act on users’ behalf, the agents and the knowledge systems they use can themselves be targeted — through injected instructions, stolen credentials or altered logs."),
 P("B05", "Conventional natural-language and speech technology, on which question answering in many languages depends, either encodes grammar, pronunciation and prosody in manually authored rules, dictionaries and language packs, which are brittle and language-specific, or trains neural models top-down on tokenized text without grounding in the acoustic and communicative foundations from which human language develops, and without exploiting the structural transfer by which a first language accelerates the acquisition of later ones."),
 P("B06", "There exists a need for a knowledge and query system in which (a) every assertion is an atomic, content-identified record carrying an evidence-based confidence, an authority certification, a verifiable provenance and its own safety classification; (b) queries evaluate structure and trust together; (c) every output is composed only from verified records and is cited or refused; (d) knowledge is independent of the language in which it arrived; (e) records are re-validated when they cross boundaries and can be erased individually without weakening the store’s integrity; (f) a single safety constraint governs every subsystem and every agent action; and (g) language and speech, identity, media and agent capabilities are built on that core and inherit its guarantees rather than weakening them."),
])

SUMMARY = """<h2>Summary of the Invention</h2>
  <p class="add">QueryBook is a deterministic, provenance-tracked federated knowledge and query system. Its core, described in Part A (FIG. 1–FIG. 22), comprises: (1) the <b>Fact Unit</b>, an immutable record encoding exactly one assertion as a nucleus of subject, predicate, object and polarity, identified by a semantic fingerprint derived from its content and carrying in its envelope an evidence-based confidence, an authority certification, a signed provenance reference, temporal anchors, typed links and an in-record safety classification and access-control list; (2) the <b>UFCS substrate</b>, a content-addressed fact graph, ontology mesh and append-only provenance ledger, with a serialized packet form and fingerprint-indexed block storage that stores identical meaning once; (3) a <b>certification authority hierarchy</b> under which each record inherits a trust ceiling from its issuing authority; (4) the <b>Federated Query Language (FQL)</b>, which evaluates structural patterns and trust thresholds together during traversal, excludes contradicted records and binds every result to a response provenance hash; (5) <b>verification</b> of any machine-generated text against certified records as verified, contradicted or unknown; (6) <b>grounded response generation</b> under a directive fixed before generation, with a vocabulary constrained to the contributing records, which cites or refuses; (7) <b>federation</b> with re-validation at every boundary and <b>fact-level erasure</b> by destruction of an external key; (8) the <b>Prime Directive</b>, a Domain-0 safety plane governing every answer, output and scheduled action, with a rule forbidding the withholding of entitled information as a means of avoiding a harm determination; and (9) <b>governed user-owned agents</b>, a layered security architecture, deployment topologies over an invariant common layer, language-independent regeneration, and provenance-carrying transport over TCP/IP.</p>
  <p class="add">Because a record’s identity is derived from its meaning rather than from its wording, the same assertion arriving in different languages or from different sources converges on one record with several provenance branches; corroboration, contradiction and duplication are detected at ingestion; and a correction is made once. Because generation draws only on the records a query returned, an ungrounded assertion is structurally unavailable to the system rather than merely discouraged, and identical inputs in an identical context produce identical output.</p>
  <p class="add">On that core the invention provides subsystems and embodiments, each inheriting the core’s guarantees: in Part B, the integral language and speech subsystem — the Language Expression Layer with its Sub-Language Priming Layer, one-way Transition Gate, multilingual Delta Acquisition, Speech Output Pipeline and co-grounding with FQL and UFCS, together with deterministic, reduced-to-practice pronunciation, speech, translation and quality-control embodiments; in Part C, voiceprint and multimodal identity linking, an independent integrity-audit service, a paralinguistic and pragmatic interpretation layer, and a lecture-query mode; and in Part D, deterministic multilingual acquisition, dialect parameter clusters, grounded scene compilation, key-safe service mediation, edition packaging, a version-independent store, cited question-and-answer and other application surfaces, meaning-based handling of pictures, sound and video, and agent-era extensions for arbitrary-artifact ingestion, on-chain certification, agent protection and deception, a tamper-evident security record, agent interoperability and framed transport.</p>
  <p class="add">No large language model asserts a fact anywhere in the system. A large language model may be used only in non-asserting roles — to phrase an answer over records the system has already verified, or to propose hypotheses for exploration — and anything it proposes is admitted only after independent verification against the deterministic store; its output, where retained, is marked as externally generated and is inadmissible as a grounding source.</p>
"""

BRIEF_CORE = {
 1: "a block diagram of the overall QueryBook system architecture, in which multimodal ingestion, the UFCS substrate, FQL query execution, verification, grounded generation, content-addressed storage and federation each execute beneath the Prime Directive operating as a Domain-0 safety plane",
 2: "a diagram of the Fact Unit, showing its nucleus, the derivation of its semantic fingerprint and identifier from content, and the confidence, provenance, certification, temporal, safety and link fields of its envelope",
 3: "a diagram of the fact-certification authority hierarchy, in which trust flows downward from a root trust anchor and each certified record inherits a trust ceiling from its issuing authority class",
 4: "a block diagram of the UFCS substrate, comprising a fact graph, an ontology mesh and a provenance ledger keyed by content fingerprint, and the pairwise, hyperedge and directed-hyperchain relationship types",
 5: "a diagram of authored tour and exhibition sequencing, in which an author fixes the order of immersive scenes at waypoints and the reader controls pace and direction",
 6: "a flow diagram of FQL joint structure and trust execution, in which structural filtering, trust propagation, branch-and-bound pruning and contradiction exclusion operate together during traversal to produce ranked results bound to a response provenance hash",
 7: "a flow diagram of the verification of machine-generated text against certified records, classifying each extracted assertion as verified, contradicted or unknown",
 8: "a diagram of federation, in which a certified envelope crossing from one domain to another is re-validated by the receiving domain before admission",
 9: "a diagram of fact-level erasure, in which a sealed record’s encrypted payload is rendered unrecoverable by destroying an externally held key",
 10: "a diagram of the universal security architecture, showing twelve defensive layers, five postures and AI-attack prediction",
 11: "a diagram of universal honeypot saturation and the data firehose, in which real assets are concealed among indistinguishable decoys",
 12: "a diagram of deployment topologies — cloud, local server, hybrid, single-device and edge — over an invariant common layer and a governed agent runtime",
 13: "a flow diagram of the adaptive response engine, in which a response directive and vocabulary constraint are fixed before generation",
 14: "a flow diagram of the user-owned agent system, in which every agent action is evaluated by governance within its commissioner’s authority and the commissioner holds a kill and revoke control",
 15: "a diagram of deterministic multi-language regeneration, in which content ingested once is regenerated on demand in each target language from one language-independent Fact Unit graph",
 16: "a diagram of semantic compression, expansion, colorization and upscaling of media over a meaning store",
 17: "a diagram of the QueryBook-enhanced TCP/IP hybrid protocol packet, carrying an optional semantic metadata header between the transport header and the payload",
 18: "a diagram of the neuromorphic cognitive layer, in which a noisy cue converges on a stored equilibrium of an attractor network below a capacity ceiling",
 19: "a diagram of the Fact Unit confidence and evidence model, comprising an evidence pair, a Beta posterior, a score, a credible interval, source diversity, temporal decay and a confidence trend",
 20: "a diagram of the UFCS packet structure, showing the fields of a serialized Fact Unit record and an exemplar packet",
 21: "a diagram of UFCS packet framing, in which immutable packets are de-duplicated by fingerprint and appended to content-addressed blocks under a fingerprint index",
 22: "a diagram of FQL query anatomy with a worked example, in which match, where, exclude, rank and return clauses produce a highest-trust answer bound to its evidence by a provenance hash",
}

PART_HEAD = lambda t: f'<h3 class="add">{t}</h3>\n'
SEC = lambda sid, t: f'<h4 id="{sid}" class="add">{t}</h4>'

PART_A = PART_HEAD("Part A — The QueryBook Core Platform (FIG. 1–FIG. 22)") + "".join([
 SEC("sec-a1", "Section I — System Architecture and the Prime Directive (FIG. 1)"),
 P("A01", "With reference to FIG. 1, QueryBook is a fact-grounded knowledge and query system. It is not a generative language model, an agent framework or a retrieval-augmented generator: every output of the system is derived from Fact Units — discrete, typed, atomic knowledge records — rather than generated as unconstrained text. Content enters through multimodal ingestion (6102), which converts it into Fact Units admitted to the UFCS substrate (6100) comprising a fact graph, an ontology mesh and a provenance ledger. A query is executed by FQL (6104), which evaluates structure and trust jointly; verification (6106) classifies assertions as verified, contradicted or unknown against a ledger; grounded generation (6110) composes cited output only from the records a query returned; a storage engine holds content-addressed blobs; and federation (6108) re-validates every record crossing a domain boundary."),
 P("A02", "Every stage executes beneath the Prime Directive (6112), a safety substrate operating as Domain 0. The Prime Directive provides that the system shall not, through any query answer, commerce signal, generated output, knowledge content, or automated or scheduled action, cause or materially contribute to harm to a person, a group of people or the operator’s organization where that harm could reasonably have been avoided without withholding information the requester is entitled to receive. No subsystem is exempt and none may be configured to bypass it. A companion Without-Information Rule forbids withholding information a requester is entitled to receive as a means of avoiding a harm determination, so that a denial is a deny-with-guarantee: a request that is refused still returns the information to which the requester is entitled."),
 P("A03", "Domain 0 is a vertical domain penetrating every horizontal domain of the system and owns, in addition to the constraint itself, the safety enforcement plane, a transfer matrix governing every permitted movement of data between domains, a path-separation invariant, and the scheduling priority ordering. These mechanisms belong to a permanently excluded set that no change proposal may reach: the system’s own improvement process requires the approval of a named, accountable human at a non-bypassable gate, and the excluded set is structurally unreachable regardless of the evidence offered for a change."),
 P("A04", "The architecture provides two guarantees that conventional systems do not. Groundedness is structural: the system is arranged in layers — substrate, structure, convergence, inference and expression — such that expression cannot write to the substrate and generation composes only under a vocabulary traceable to the records beneath, so that an ungrounded assertion has no route by which to reach the reader. Determinism is defined: two executions are required to produce identical output wherever a context key computed over an enumerated set of locked context dimensions (for example entitlement set, locale, register and audience level) is identical, and a difference between such executions is a defect."),
 SEC("sec-a2", "Section II — The Fact Unit (FIG. 2, FIG. 19)"),
 P("A05", "With reference to FIG. 2, the fundamental data primitive of the system is the Fact Unit. A fact envelope (6200) surrounds a nucleus (6202) encoding exactly one assertion as a subject, a predicate, an object and a polarity — for example, subject France, predicate has_capital, object Paris, polarity affirmative. The subject and object are canonical, language-neutral identifiers and the predicate is drawn from a governed predicate catalogue; a predicate not in the catalogue cannot be asserted, and a candidate record lacking a required field is refused at construction rather than admitted and flagged. A passage stating three things becomes three Fact Units, which is what allows a response to cite the specific assertion it relied upon."),
 P("A06", "Identity is derived from content rather than assigned. The subject, predicate, object and polarity are normalized and hashed (in the embodiment, by SHA-256) to produce a semantic fingerprint (6204), which is independent of the language and wording of the source; and a Fact Unit identifier (6206) is derived by hashing the content together with its source and ingestion time. Two records asserting the same thing — including in different natural languages — therefore carry the same fingerprint and converge upon one record with several provenance branches, which enables de-duplication, corroboration and contradiction detection at ingestion: a record with the same subject and predicate but a different object, or the same assertion with opposite polarity, is detected as a contradiction rather than stored as an unrelated record."),
 P("A07", "The envelope carries: a confidence (6208); a provenance reference (6210) comprising a ledger reference, a chain index and a digital signature (Ed25519 in the embodiment); a certification (6212) comprising the issuing authority class and a trust score; temporal fields (6214) distinguishing when the assertion held (its anchor), when it was ingested and when it was attested; a safety classification and access-control list (6216) carried within the record, so that entitlement is a property of the assertion rather than a filter over a result and no code path reaches the assertion without it; and typed links (6218) to other Fact Units. A Fact Unit is immutable once sealed: a revision produces a new, linked version identifying the record it supersedes, and a record derived rather than reported — an inference, a reconstruction, or an assertion generated by a named external engine — carries an unremovable derivation marking and is inadmissible as a grounding source."),
 P("A08", "With reference to FIG. 19, the confidence is not a scalar but a governed evidence estimate. An evidence pair (7900) accumulates supporting evidence α and contradicting evidence β, defining a Beta posterior (7902) over the truth of the assertion; the reported score (7904) is α/(α+β), and a credible interval (7906), for example at 95%, is computed from the evidential weight α+β. Source diversity (7908) measures the spread of contributed weight across registered source classes, so that independent corroboration counts for more than repetition within one class. Temporal decay (7910) moves the parameters toward the prior, widening the interval while preserving the reported score, and a confidence trend (7912) reports whether the confidence is ascending, stable or descending. Two records with an identical score but different quantities or varieties of evidence are thereby distinguishable."),
 P("A09", "An explicit polarity makes a negative finding a first-class record. The system accordingly distinguishes the absence of any record, which obliges it to answer that it does not know, from a known negative, which is an answer."),
 SEC("sec-a3", "Section III — The UFCS Substrate and Record Format (FIG. 4, FIG. 20, FIG. 21)"),
 P("A10", "With reference to FIG. 4, the Universal Federated Connectivity System (UFCS) substrate comprises three stores: a fact graph (6402) whose nodes are Fact Units joined by typed edges; an ontology mesh (6404) of shared concepts that binds subjects and predicates to canonical identifiers; and a provenance ledger (6406) that is append-only and records signed lineage. Every node and edge is keyed by content fingerprint. The substrate supports three relationship types (6408): a pairwise edge; a hyperedge, in which one relation holds among a set of Fact Units — for example a reaction with several reactants and products, or a contract with several parties — so that the constituents are not falsely decomposed into pairs; and a directed hyperchain."),
 P("A11", "With reference to FIG. 20, a Fact Unit is serialized as a UFCS packet comprising a header (8000) carrying the format version, the identifier, the fact type and the domain; the nucleus (8002); the identity (8004) carrying the semantic fingerprint; the confidence (8006) carrying α, β, the score and the credible interval; the sources (8008), each with an identifier, name, class and reputation; the certification (8010); the temporal fields (8012); the provenance (8014) carrying the ledger reference, chain index and signature; the safety fields (8016); and the links (8018), including typed relations and an embedding reference. An exemplar packet (8020) is shown. The packet is the record’s own canonical encoding, so that a host database holds it as opaque bytes and is never required to parse it; any store therefore qualifies, the system’s guarantees travel with the record, and an external store serves as a repository and never as the reasoning engine."),
 P("A12", "With reference to FIG. 21, a packet stream (8100) is written by a block writer (8102) that de-duplicates by fingerprint and appends immutable packets to content-addressed blocks (8104) — in the embodiment of approximately one gigabyte each, compressed — under a fingerprint index (8106) that provides constant-time de-duplication and retrieval. Identical meaning yields an identical fingerprint and is stored once, and corroboration and contradiction are detected at ingestion."),
 SEC("sec-a4", "Section IV — Certification and the Federated Query Language (FIG. 3, FIG. 6, FIG. 22)"),
 P("A13", "With reference to FIG. 3, certification descends from a self-certifying root trust anchor (6300) through certifying authority classes (6302). Trust flows downward: a Fact Unit inherits a trust ceiling from the authority class that certified it. In the illustrated example the ceilings are 0.93 for a government authority, 0.86 for an academic authority, 0.80 for a publisher and 0.62 for a web-crawl authority; the classes and values are configurable and are shown by way of example."),
 P("A14", "With reference to FIG. 6, a query (6600) in the Federated Query Language combines a structural pattern with a trust threshold τ. A structure filter (6602) matches subject, predicate and object patterns; trust propagation (6604) combines the trust of contributing sources; branch-and-bound (6606) prunes any candidate falling below τ during traversal rather than as a post-filter; contradiction exclusion (6608) removes records in unresolved conflict; and the ranked results (6610) are returned together with a response provenance hash identifying the contributing records. Because structure and certification are evaluated together, an untrusted path is never traversed to completion."),
 P("A15", "With reference to FIG. 22, a worked example comprises a MATCH clause (8200) for subject France, predicate has_capital and an unknown object; a WHERE clause (8202) requiring a trust score of at least 0.70; an EXCLUDE clause (8204) removing contradicted or unresolved records; a RANK BY clause (8206) ordering by trust; and a RETURN clause (8208) returning the object together with the response provenance hash. The result (8210) returns Paris at trust 0.776, verified, while a lower-trust candidate (Lyon at 0.434) is excluded; the hash binds the returned answer to its evidence so that any party can verify which records the answer rests on."),
 P("A16", "Every query is evaluated against the requesting identity’s licensed content scope before execution: a record outside the scope is not traversable, rather than being removed from a result afterwards. Natural-language input in any supported language is resolved to an FQL operation by the language subsystem of Part B (Section XIV), so that the query layer itself is language-agnostic."),
 SEC("sec-a5", "Section V — Verification and Grounded Response Generation (FIG. 7, FIG. 13)"),
 P("A17", "With reference to FIG. 7, any machine-generated text — whether composed by the system or received from an external generator — is verified before it reaches a reader. Each assertion (6700) is extracted and its fingerprint is matched against certified records: a match is classified verified (6702); otherwise the system tests whether a certified record has the same subject and predicate but a different object (6704) and, if so, classifies the assertion contradicted (6708), citing the higher-trust record; and where no candidate exists the assertion is classified unknown (6706)."),
 P("A18", "With reference to FIG. 13, an adaptive response engine composes a response in five stages: result-set analysis (7300); profile resolution (7302), establishing the audience level, register, locale and entitlements of the requester; directive assembly (7304); a vocabulary constraint (7306) limiting the permissible terms to those traceable to the contributing Fact Units; and generation (7308) under the directive. The directive is frozen before generation begins and is not renegotiated during generation, so the response cannot drift from what the evidence supports."),
 P("A19", "A response cites each Fact Unit on which it relies. Where no record satisfies the query, the system answers that it does not know rather than producing a plausible answer, and where a record establishes a negative, the system reports the negative as the answer. The same cite-or-refuse contract applies when the response is rendered in another language or as speech."),
 SEC("sec-a6", "Section VI — Federation and Fact-Level Erasure (FIG. 8, FIG. 9)"),
 P("A20", "With reference to FIG. 8, a Fact Unit certified in a first domain (6800) is transferred to a second domain (6802) as a certified envelope (6804) carrying its fingerprint, signature and certifying authority. The receiving domain performs re-validation (6806) — re-checking the signature and the trust against its own authority ceilings — before admission. A certification is never trusted blindly across a boundary, and the admitted record carries a provenance branch identifying its origin."),
 P("A21", "With reference to FIG. 9, the payload of a sealed Fact Unit (6900) may be encrypted under a key held outside the system (6902). Destroying that key (6904) renders the payload unrecoverable and inert (6906), so that a single record can be erased — for example to honour a lawful erasure request — while the content-addressed store remains otherwise append-only and immutable and its integrity chain remains verifiable. Where a user elects passphrase-derived encryption of the user’s own history, the platform cannot decrypt that history, and account erasure is likewise effected by key destruction."),
 SEC("sec-a7", "Section VII — Governed Agents, Security, Deployment and Application Surfaces (FIG. 10–FIG. 12, FIG. 14, FIG. 48, FIG. 49)"),
 P("A22", "With reference to FIG. 14, a user may own agents. An agent blueprint (7400) is defined and registered; an agent instance (7402) holds authority bounded by its commissioner; each action (7404) is permitted only within the intersection of the blueprint’s action template and the commissioner’s entitlement and is subjected to a governance evaluation (7406) at every action, resulting in allow and execute (7408) or deny and log (7410). The commissioner holds an unconditional kill and revoke control (7412) by which the instance may be halted at any time. An agent can never exceed its commissioner, and an external platform connected to the system receives only specific, declared actions rather than general authority."),
 P("A23", "With reference to FIG. 10, the system’s security architecture comprises twelve defensive layers (7000) — an AI execution zone, an AI security gateway, a worm-resistant credential, behavioral detection, behavioral endpoint detection and response, an automated kill switch, supply-chain protection, provenance integrity, honeypot saturation, attack prediction, a post-quantum ledger and governance oversight — organized under five postures (7002) and informed by AI-attack prediction (7004). The postures are architectural categories; the embodiment reduced to practice (Section XXIII) operates in a defensive and observational posture only."),
 P("A24", "With reference to FIG. 11, honeypot saturation conceals real assets among decoys: a phantom port daemon (7102) answers on every port, a shadow-application mechanism (7104) presents fake entry points, and a data firehose (7106) returns responses of apparently unlimited volume, so that an attacker sees only decoys and real assets become statistically unfindable."),
 P("A25", "With reference to FIG. 12, the system is deployable in a cloud software-as-a-service topology (7200), a local-server topology (7201), a hybrid topology (7202), a single-device topology (7203) and an edge topology (7204), the edge holding no authority of its own and escalating where entitlement requires. In every topology an invariant common layer (7210) — the Prime Directive, the transfer matrix, path separation and provenance — and a governed agent runtime (7212) are identical; only the topology varies. Offline operation is reconciled with a hosted deployment through a defined synchronization layer."),
 P("A26", "With reference to FIG. 48, a cited question-and-answer application (4800) receives a typed or spoken user question (4801), interprets it for intent and register (4810), retrieves verified Fact Units by FQL (4820), and passes the result through the Prime-Directive gate (4830), which returns either a composed answer carrying per-fact citations (4840) or, where the evidence is insufficient, an honest UNKNOWN (4841), the system refusing rather than guessing; the same contract holds when the answer is delivered through a chatbot or assistant surface (4850), so that no large language model asserts a fact anywhere along the path (4860). With reference to FIG. 49, the invariant core (4900) is presented through further surfaces — an on-device, micro-encapsulated eBook or document question-and-answer surface (4910), a software-as-a-service or programmatic-interface service (4920), a Fact-Unit compressed search engine (4930), a deterministic adjunct to a large language model acting as a gated suggestor (4940), and a private or offline analysis deployment (4950) — each a presentation of the same governed Fact Units, inheriting the same citation-or-UNKNOWN contract and provenance (4960), and none able to assert a fact the core would refuse."),
 SEC("sec-a8", "Section VIII — Language Independence, Transport, Media, Presentation and the Cognitive Layer (FIG. 5, FIG. 15–FIG. 18)"),
 P("A27", "With reference to FIG. 15, source content is ingested once (7500) into a language-independent Fact Unit graph (7502), from which responses are regenerated on demand in any of a plurality of target languages (7504) — for example English (7504a), Japanese (7504b), Spanish (7504c) and Arabic (7504d) — without per-language re-ingestion. Each language rendering is composed directly from the records under the same vocabulary constraint, rather than by translating an already-generated response; a wording-operative span such as a quotation or a statutory phrase is reproduced verbatim in its source language with a separately marked gloss; and the same assertion attested in two languages counts as corroboration from two source classes. The language and speech capability on which this rests is the subsystem of Part B."),
 P("A28", "With reference to FIG. 17, a Fact Unit transmitted over a TCP/IP network may carry, between the IP header (7700) and TCP header (7702) on one side and the payload (7706) on the other, an optional semantic metadata header (7704) comprising the Fact Unit identifier, a provenance reference and the confidence. An endpoint not participating in the scheme ignores the header, so that provenance travels with the bits while the packet remains backward-compatible. A framed transport extending this packet, with priority lanes and rebuild into standard streaming formats, is described in Section XXIII (FIG. 55)."),
 P("A29", "With reference to FIG. 16, media is handled by recording its meaning rather than its surface: media (7600) is reduced by semantic compression (7602) to records in a meaning store (7604), from which expansion (7606), colorization from material-property facts (7608) and upscaling (7610) regenerate a surface that is marked as regenerated wherever it was not present in the source. This design, and the part of it reduced to practice, are described in Sections XXII and XXIII."),
 P("A30", "With reference to FIG. 5, an author may fix the order of a presentation as a sequence of waypoints (6500–6504), each an immersive scene composed from Fact Units, in an author-selected order (6510), while reader playback control (6512) lets the reader move backward, pause and advance along the ordered waypoints. The author controls the sequence; the reader controls the pace and direction."),
 P("A31", "With reference to FIG. 18, a neuromorphic cognitive layer — the term denoting only that the organizing principle is drawn from an established result in neuroscience, and not that any neural network or spiking hardware is used — resolves an ambiguous candidate set by convergence. An attractor network iteratively updates activation values so as to decrease monotonically an energy (7800), E = −½ Σ w<sub>ij</sub> a<sub>i</sub> a<sub>j</sub>, so that a partial or noisy cue (7806) relaxes to the nearest stable equilibrium (7802); the number of stored configurations is held below a capacity ceiling (7804), illustrated as α<sub>c</sub> ≈ 0.138, above which retrieval states cease to exist. The convergence is deterministic and nothing is sampled."),
 P("A32", "<b>Status of Part A.</b> The Fact Unit with its content-derived fingerprint, sealing into a hash-chained provenance ledger, trust-thresholded querying with cite-or-refuse answering, verification of text against stored records, governed agents and the agent gateway are embodied in the working QueryBook software prototype referred to in Parts B and D. The remaining elements of Part A — including the certification-authority ceilings, the neuromorphic convergence layer, honeypot saturation, the twelve-layer security architecture and the full set of deployment topologies — are specified designs and are not asserted to be reduced to practice. Numerical values shown in the drawings, such as trust ceilings, block size and the capacity ceiling, are illustrative."),
])

PART_B_HEAD = PART_HEAD("Part B — The Language and Speech Subsystem (FIG. 23–FIG. 32)") + \
 '<p class="add">The following sections describe QueryBook’s integral language and speech subsystem, the Language Expression Layer (LEL), by which natural-language input in any supported language resolves to the FQL representation of Section IV and results are rendered back as language or speech in the language of the query. The subsystem operates over the Fact Units of Part A and inherits their determinism, provenance and cite-or-refuse guarantees.</p>\n'
PART_C_HEAD = PART_HEAD("Part C — Identity, Integrity-Audit, Interpretation and Lecture Embodiments (FIG. 33–FIG. 40)") + \
 '<p class="add">The following embodiments apply the core of Part A and the language subsystem of Part B to speaker identity, independent integrity audit, the interpretation of how things are said, and the ingestion of spoken programs. Each records what it observes as attributed, provenance-tracked Fact Units and never promotes an estimate to an asserted fact.</p>\n'
PART_D_HEAD = PART_HEAD("Part D — Further Embodiments, Media and Agent-Era Extensions (FIG. 41–FIG. 55)") + \
 '<p class="add">The following embodiments extend the system of Parts A to C — in multilingual acquisition, dialects, media generation and handling, packaging and store continuity, and the protection and interoperation of AI agents — each under the Prime Directive and the governed-fact contract of Part A. The cited question-and-answer and deployment surfaces of FIG. 48 and FIG. 49 are described in Section VII.</p>\n'

CORE_CLAIMS = [
 "A computer-implemented knowledge and query system, comprising one or more processors and memory storing: a knowledge substrate of Fact Units, each Fact Unit encoding exactly one assertion as a nucleus comprising a subject, a predicate, an object and a polarity, and an envelope carrying a confidence, a provenance reference into an append-only provenance ledger, a certification by an issuing authority, a temporal anchor, and a safety classification and access-control list carried within the Fact Unit, each Fact Unit being immutable once sealed and identified by an identifier derived from its content; a query engine configured to execute a query combining a structural pattern over subjects, predicates and objects with a trust threshold, evaluating structure and certification together during traversal, and returning results bound to a response provenance value identifying the contributing Fact Units; a grounded-generation stage configured to compose a natural-language response only from Fact Units returned by the query engine, citing each contributing Fact Unit, and to return an indication that the answer is unknown where no Fact Unit satisfying the trust threshold exists; and a safety plane configured to gate every query answer, generated output and scheduled action of the system, a denial by the safety plane returning information the requester is entitled to receive.",
 "The system of claim 1, wherein said identifier comprises a semantic fingerprint computed by a cryptographic hash over a normalized form of the subject, predicate, object and polarity, such that two Fact Units asserting the same assertion, including in different natural languages, carry the same fingerprint and are de-duplicated, corroborated or detected as contradictory at ingestion.",
 "The system of claim 1, wherein the confidence comprises a first parameter accumulating supporting evidence and a second parameter accumulating contradicting evidence, a score equal to the ratio of the first parameter to the sum of the parameters, a credible interval, a source-diversity measure over registered source classes, a temporal decay that widens the credible interval while preserving the score, and a trend indicating whether the confidence is ascending, stable or descending.",
 "The system of claim 1, wherein each certification is issued under an authority hierarchy descending from a root trust anchor, each authority class imposing a trust ceiling inherited by the Fact Units it certifies.",
 "The system of claim 1, wherein the knowledge substrate comprises a fact graph whose nodes are Fact Units joined by typed edges, an ontology mesh binding subjects and predicates to canonical language-neutral identifiers, and said provenance ledger, every node and edge being keyed by content fingerprint, and a relation among more than two Fact Units being held as a single hyperedge.",
 "The system of claim 1, wherein the query engine propagates trust from contributing sources, prunes a candidate falling below the trust threshold during traversal, excludes Fact Units in unresolved contradiction, and ranks the results by trust.",
 "The system of claim 1, further comprising a verifier configured to extract each assertion from machine-generated text and to classify it, before the text is delivered to a reader, as verified where its fingerprint matches a certified Fact Unit, as contradicted where a certified Fact Unit has the same subject and predicate and a different object, the verifier citing the higher-trust Fact Unit, and as unknown where no candidate Fact Unit exists.",
 "The system of claim 1, further comprising a federation interface by which a Fact Unit certified in a first domain is admitted into a second domain only after the second domain re-validates its signature and its trust against the second domain’s authority ceilings.",
 "The system of claim 1, wherein a payload of a sealed Fact Unit is encrypted under a key held outside the system, and the Fact Unit is erased by destroying said key while the content-addressed store otherwise remains append-only.",
 "The system of claim 1, wherein each Fact Unit is serialized as a packet comprising a header, the nucleus, the semantic fingerprint, the confidence, its sources, the certification, temporal fields, the provenance reference with a digital signature, safety fields and typed links, and wherein packets are appended to content-addressed blocks under a fingerprint index such that a Fact Unit having an identical fingerprint is stored once.",
 "The system of claim 1, wherein the safety plane is a domain penetrating every other domain of the system and owns a transfer matrix governing each permitted movement of data between domains and a path-separation invariant, and wherein a rule prohibits withholding information a requester is entitled to receive as a means of avoiding a harm determination.",
 "The system of claim 1, further comprising an adaptive response engine configured to analyze a result set, resolve a profile of the requester, assemble a response directive and a vocabulary constraint limited to terms traceable to the contributing Fact Units, and fix the directive before generation begins, generation proceeding under the directive without renegotiation.",
 "The system of claim 1, wherein the grounded-generation stage renders a response in any of a plurality of natural languages directly from the same language-independent Fact Units, without per-language re-ingestion and without translating a previously generated response, each rendering being subject to the same citation requirement.",
 "The system of claim 1, further comprising a governed agent runtime in which an agent instance created from a registered blueprint holds authority bounded by its commissioner, each action of the agent being permitted only within the intersection of an action template of the blueprint and the commissioner’s entitlement and being evaluated by governance before execution, denied actions being logged, and the commissioner holding an unconditional control to halt or revoke the agent instance.",
 "The system of claim 1, deployable in each of a cloud, a local-server, a hybrid, a single-device and an edge topology, wherein the safety plane, a transfer matrix, path separation, provenance and a governed agent runtime form a common layer that is identical across said topologies.",
 "The system of claim 1, wherein a Fact Unit transmitted over a TCP/IP network carries, between a transport header and a payload, an optional semantic header comprising its identifier, a provenance reference and its confidence, an endpoint not participating in the semantic header ignoring it.",
 "The system of claim 1, further comprising a convergence layer configured to resolve a candidate set of Fact Units to a stable configuration by a deterministic iterative update that monotonically decreases an energy over the configuration, the number of stored configurations being held below a capacity ceiling, and no value being sampled.",
 "A computer-implemented method of answering a query, comprising: receiving a query expressed in a natural language; resolving the query to canonical subject and predicate identifiers; executing, over a store of immutable Fact Units each encoding one assertion and carrying a content-derived fingerprint, a confidence, a certification, a provenance reference and an in-record safety classification, a query that combines a structural pattern with a trust threshold during traversal; composing an answer only from the Fact Units returned, with a citation to each contributing Fact Unit and a provenance value binding the answer to those Fact Units; returning an indication that the answer is unknown where no Fact Unit satisfies the query; and rendering the answer in the natural language of the query, every step being gated by a safety plane that governs every output of the system.",
 "A computer-implemented method of governing machine-generated content, comprising: receiving text generated by a generative process; extracting from the text a plurality of assertions; for each assertion, computing a language-independent semantic fingerprint over a normalized subject, predicate, object and polarity of the assertion; classifying the assertion as verified where the fingerprint matches a certified Fact Unit, as contradicted where a certified Fact Unit has the same subject and predicate and a different object, and as unknown otherwise; and delivering the text to a reader only together with said classifications and, for each contradicted assertion, a citation to the contradicting Fact Unit having the higher trust.",
 "A non-transitory computer-readable medium storing instructions which, when executed by one or more processors, cause the one or more processors to perform the method of claim 18.",
]

ABSTRACT = ('<h2>Abstract</h2>\n  <p class="add">A deterministic, provenance-tracked federated knowledge and query system (QueryBook) holds knowledge as immutable '
 'Fact Units, each encoding one assertion with a content-derived semantic fingerprint and carrying an evidence-based confidence, an '
 'authority certification, a signed provenance reference, a temporal anchor and an in-record safety classification. A Federated Query '
 'Language evaluates structural patterns and trust thresholds together during traversal over a content-addressed substrate. Responses '
 'are composed only from returned records, cite each contributing Fact Unit with a provenance hash, and are refused as unknown where no '
 'record suffices; machine-generated text is classified as verified, contradicted or unknown. Records crossing domains are re-validated, '
 'and a record is erasable by destroying its external key. A Prime Directive operating as a Domain-0 safety plane governs every output '
 'and agent action. Integral subsystems provide multilingual language and speech, identity, audit, media and agent-protection '
 'capabilities under the same guarantees.</p>\n')

FLAG = ('<div class="foot add" style="border-left:4px solid #b25d00;padding-left:12px;margin-bottom:10px;background:#fbf7f0;'
        'border-top:none;padding-top:10px;padding-bottom:10px"><b style="color:#b25d00">')
NEW_FLAGS = [
 FLAG + "COUNSEL FLAG — rebalanced, QueryBook-first structure (rev. October 8, 2026 (B)).</b> The application was previously framed around the language subsystem: its title, Field, Background, Summary, Abstract, FIG. 1–8 and claims 1–30 were directed to the LEL, and the QueryBook platform figures had no detailed description and no independent claims. This revision (a) retitles the application to the QueryBook system and rewrites the Field, Background, Summary and Abstract QueryBook-first; (b) adds Part A ({A01}–{A32}), the detailed description of the core platform figures; (c) adds independent and dependent core-platform claims 1–20; (d) renumbers the figures from the core outward (former FIG. 9–30 → FIG. 1–22; former FIG. 1–8 → FIG. 23–30; FIG. 31–55 unchanged), with paragraphs, sections and claims renumbered and every cross-reference updated; (e) moves the platform reference numerals to a 6100–8210 series, resolving their collision with the language and identity numerals, and adds them to the Reference Numerals key; (f) relocates the brief descriptions of FIG. 31–49 from Section IX to the Brief Description of the Drawings; and (g) corrects FIG. 5 by removing a stray “(CLAIM 11)” label, removing overlay boxes that hid the waypoint labels, and replacing the undefined label “(IQR)” with “from Fact Units”. This addresses items (b) and (c) of the consolidation flag below. The substantive content of Parts B–D is unchanged apart from renumbering, short part introductions, and the consolidation of the Section XXIII claims noted below.</div>\n",
 FLAG + "COUNSEL FLAG — core claims 1–20 and the related QueryBook provisionals.</b> The core platform (Fact Unit, UFCS, FQL, Prime Directive, certification, federation, erasure) is also the subject of the prior QueryBook, UFCS and FQL provisional applications listed under Related applications. Claims 1–20 may overlap claims of those applications and may be entitled to their priority. Please confirm the priority claims and any incorporation by reference, and decide whether the core claims are pursued here, in the core family, or both. Expect relevant art in knowledge graphs and provenance models, trust-weighted and probabilistic databases, verification of generated text against a knowledge base, cryptographic erasure (crypto-shredding), content-addressed storage and federated data systems; the claims are framed on the combination recited in claim 1.</div>\n",
 FLAG + "COUNSEL FLAG — Part A reduction-to-practice status.</b> {A32} states which core-platform elements are embodied in the QueryBook software prototype and which are specified designs. Please confirm that characterization against the prototype before filing, and confirm that no specified element reads as performed. Numerical values in FIG. 3, FIG. 18 and FIG. 21 are illustrative.</div>\n",
 FLAG + "COUNSEL FLAG — Section XXIII claims consolidated for proportion.</b> The agent-era claims added earlier in this revision cycle were reduced from 23 to 12 (now claims 97–108) so that the claim set reflects the system as a whole rather than its most recent extension. The omitted dependent subject matter remains disclosed in Section XXIII and may be claimed on conversion: typed record kinds and repeatable re-ingestion; archive bounds and non-execution; recovery of page-description text through character-to-Unicode maps; the certificate-is-not-a-truth-claim presentation; the in-system transaction signer with test-vector self-checks and the value-bearing-network guard; the token-holder licence check; firewall signatures and per-caller anomaly scoring; the loopback client key; treating a purge request as a tripwire; the tool-server interface; and leaving skin regions uncolored absent a record.</div>\n",
]

FINAL_FOOT = ('<div class="foot add">\n    DRAFT — NOT FILED — FOR REVIEW BY QUALIFIED PATENT COUNSEL PRIOR TO FILING. Provisional application '
 'under 35 U.S.C. § 111(b); not examined. Audit-marked refinements strengthen enablement and are subject to counsel review. A '
 'professional prior-art search is required before filing; expect relevant art in knowledge graphs and provenance models, '
 'trust-weighted query, retrieval-augmented generation and output verification, cryptographic erasure, federated data systems and '
 'AI-agent security and, for the language subsystem, in self-supervised speech representation learning, curriculum learning, '
 'cross-lingual transfer, neural text-to-speech and developmental language grounding. The claimed novelty resides in the '
 'combination of content-addressed Fact Units carrying evidence-based confidence, certification, provenance and in-record safety with '
 'trust-integrated federated query, cite-or-refuse generation and Domain-0 governance, and in the subsystems built on that core, '
 'including the integrated developmental language sequence, the threshold-governed transition gate, the delta acquisition model and '
 'the LEL–FQL co-grounding. Inventors, docket number and filing date to be completed by counsel.\n  </div>\n')

# platform numeral names (new 6000-series), from the drawings
PLATFORM_NUMERALS = {
 6100: "UFCS substrate (fact graph, ontology mesh, provenance ledger)", 6102: "multimodal ingestion", 6104: "FQL query (joint structure + trust execution)",
 6106: "verification (verify / contradict / unknown)", 6108: "federation re-validation", 6110: "grounded generation (cited output)",
 6112: "Prime Directive safety substrate (Domain 0)",
 6200: "fact envelope", 6202: "nucleus (subject, predicate, object, polarity)", 6204: "semantic fingerprint", 6206: "Fact Unit identifier (FUID)",
 6208: "confidence (α / β, score, credible interval)", 6210: "provenance (reference, chain index, signature)", 6212: "certification (authority class, trust score)",
 6214: "temporal (anchor, ingested, attestation)", 6216: "safety (classification, access-control list)", 6218: "typed links to other Fact Units",
 6300: "root trust anchor", 6302: "certifying authority class with trust ceiling",
 6402: "fact graph", 6404: "ontology mesh", 6406: "provenance ledger", 6408: "substrate relationship types",
 6500: "waypoint (immersive scene) 1", 6501: "waypoint 2", 6502: "waypoint 3", 6503: "waypoint 4", 6504: "waypoint 5",
 6510: "author-selected order", 6512: "reader playback control",
 6600: "FQL query (structure pattern + trust threshold)", 6602: "structure filter", 6604: "trust propagation", 6606: "branch and bound",
 6608: "contradiction exclusion", 6610: "ranked results with response provenance hash",
 6700: "extracted assertion", 6702: "verified", 6704: "same subject/predicate, different object test", 6706: "unknown", 6708: "contradicted (higher-trust citation)",
 6800: "first domain", 6802: "second domain", 6804: "certified envelope", 6806: "re-validation before admission",
 6900: "sealed fact with encrypted payload", 6902: "external key held off-system", 6904: "key destruction", 6906: "unrecoverable payload",
 7000: "twelve defensive layers", 7002: "five postures", 7004: "AI-attack prediction",
 7102: "phantom port daemon", 7104: "shadow-application mechanism", 7106: "data firehose",
 7200: "cloud SaaS topology", 7201: "local-server topology", 7202: "hybrid topology", 7203: "single-device topology", 7204: "edge topology",
 7210: "invariant common layer", 7212: "governed agent runtime",
 7300: "result-set analysis", 7302: "profile resolution", 7304: "directive assembly", 7306: "vocabulary constraint", 7308: "generation under directive",
 7400: "agent blueprint", 7402: "agent instance", 7404: "action (template ∩ entitlement)", 7406: "governance evaluation", 7408: "allow / execute",
 7410: "deny / log", 7412: "kill / revoke switch",
 7500: "source content ingested once", 7502: "language-independent Fact Unit graph", 7504: "target languages",
 "7504a": "English rendering", "7504b": "Japanese rendering", "7504c": "Spanish rendering", "7504d": "Arabic rendering",
 7600: "media (pixels / waveform)", 7602: "semantic compression", 7604: "meaning store", 7606: "expansion", 7608: "colorization", 7610: "upscaling",
 7700: "IP header", 7702: "TCP header", 7704: "semantic metadata header (optional)", 7706: "payload",
 7800: "energy function", 7802: "stable equilibrium", 7804: "capacity ceiling", 7806: "noisy cue",
 7900: "evidence pair (α, β)", 7902: "Beta posterior", 7904: "score", 7906: "credible interval", 7908: "source diversity", 7910: "temporal decay", 7912: "confidence trend",
 8000: "packet header", 8002: "packet nucleus", 8004: "packet identity (fingerprint)", 8006: "packet confidence", 8008: "packet sources",
 8010: "packet certification", 8012: "packet temporal fields", 8014: "packet provenance", 8016: "packet safety fields", 8018: "packet links", 8020: "exemplar packet",
 8100: "packet stream", 8102: "block writer (de-duplication by fingerprint)", 8104: "content-addressed block", 8106: "fingerprint index",
 8200: "MATCH clause", 8202: "WHERE clause", 8204: "EXCLUDE clause", 8206: "RANK BY clause", 8208: "RETURN clause", 8210: "query result",
}
