<?php

declare(strict_types=1);

require_once __DIR__ . '/QrCode.php';

/**
 * Print Media Companion
 *
 * Print books can't play audio or show interactive media — so each
 * chapter of the print edition gets a QR code linking to a companion
 * web page that carries the chapter's rich media: figures, AI-image
 * prompts (and later the generated images), and the audiobook chapter.
 *
 * Produces:
 *  - companionPlan()        — one QR entry per chapter plus a master entry,
 *                             each with a scannable SVG QR (generated by the
 *                             app's own pure-PHP encoder)
 *  - exportCompanionHtml()  — the single-file companion web page to upload
 *                             at the base URL, with an anchor per chapter
 *  - exportQrSheetHtml()    — a printable sheet of QR cards for the book's
 *                             interior or back matter
 */
final class PrintMediaCompanion
{
    public const DEFAULT_BASE_URL = 'https://your-domain.com/book-companion';

    /**
     * @param array<string, mixed> $book
     * @param array<string, mixed> $metadata
     * @param array<string, mixed>|null $media
     * @return array{base_url: string, master: array<string, mixed>, chapters: array<int, array<string, mixed>>}
     */
    public function companionPlan(array $book, array $metadata, ?array $media, string $baseUrl = ''): array
    {
        $baseUrl = $this->normalizeBaseUrl($baseUrl);
        $title = trim((string) ($metadata['title'] ?? 'Untitled'));
        $mediaByChapter = [];
        foreach ((array) ($media['chapters'] ?? []) as $mediaChapter) {
            $mediaByChapter[(int) $mediaChapter['number']] = (array) $mediaChapter['items'];
        }
        $chapters = [];
        foreach ((array) ($book['chapters'] ?? []) as $chapter) {
            $n = (int) ($chapter['number'] ?? 0);
            $url = $baseUrl . '#chapter-' . $n;
            $items = $mediaByChapter[$n] ?? [];
            $chapters[] = [
                'chapter' => $n,
                'title' => (string) ($chapter['title'] ?? ''),
                'url' => $url,
                'figure_count' => count($items),
                'qr_svg' => QrCode::svg($url, 3, 'Scan for chapter ' . $n . ' media'),
            ];
        }
        return [
            'base_url' => $baseUrl,
            'master' => [
                'label' => 'All media for ' . $title,
                'url' => $baseUrl,
                'qr_svg' => QrCode::svg($baseUrl, 3, 'Scan for all book media'),
            ],
            'chapters' => $chapters,
        ];
    }

    /**
     * The companion web page: upload this single file to the base URL.
     * Light, fast, and phone-first — that's where scanned QRs land.
     */
    public function exportCompanionHtml(array $book, array $metadata, ?array $media, string $baseUrl = ''): string
    {
        $e = static fn (string $v): string => htmlspecialchars($v, ENT_QUOTES, 'UTF-8');
        $baseUrl = $this->normalizeBaseUrl($baseUrl);
        $title = trim((string) ($metadata['title'] ?? 'Untitled')) ?: 'Untitled';
        $author = trim((string) ($metadata['author'] ?? '')) ?: 'the author';
        $mediaByChapter = [];
        foreach ((array) ($media['chapters'] ?? []) as $mediaChapter) {
            $mediaByChapter[(int) $mediaChapter['number']] = (array) $mediaChapter['items'];
        }
        $html = '<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">'
            . '<title>' . $e($title) . ' — Companion Media</title><style>'
            . 'body{font-family:Georgia,serif;background:#f8f4eb;color:#202431;margin:0;line-height:1.55}'
            . 'main{max-width:720px;margin:0 auto;padding:24px 16px 80px}'
            . 'header{border-bottom:2px solid #d8d0c2;padding-bottom:16px;margin-bottom:8px}'
            . 'h1{margin:.2em 0;line-height:1.1}h2{margin:2em 0 .4em;border-bottom:1px solid #d8d0c2;padding-bottom:4px}'
            . 'figure{margin:1.2em 0;text-align:center}figcaption{font-size:.85em;font-style:italic;margin-top:.4em}'
            . 'table{border-collapse:collapse;width:100%;font-size:.85em}th,td{border:1px solid #b9b2a2;padding:.3em .5em;text-align:left;vertical-align:top}'
            . '.overflow{overflow-x:auto}.prompt{font-size:.8em;color:#5a6070;background:#fff;border:1px solid #d8d0c2;border-radius:8px;padding:.6em .8em;text-align:left}'
            . 'nav a{display:inline-block;margin:2px 6px 2px 0;font-size:.9em}'
            . '</style></head><body><main>'
            . '<header><h1>' . $e($title) . '</h1><p>Companion media for the print edition · by ' . $e($author) . '</p>'
            . '<p style="font-size:.85em;color:#5a6070">You scanned a code in the book — every chapter\'s media lives on this page. Audio and generated images appear here as the author publishes them.</p></header>'
            . '<nav aria-label="Chapters">';
        foreach ((array) ($book['chapters'] ?? []) as $chapter) {
            $n = (int) $chapter['number'];
            $html .= '<a href="#chapter-' . $n . '">Ch. ' . $n . '</a>';
        }
        $html .= '</nav>';
        foreach ((array) ($book['chapters'] ?? []) as $chapter) {
            $n = (int) $chapter['number'];
            $html .= '<h2 id="chapter-' . $n . '">Chapter ' . $n . ': ' . $e((string) $chapter['title']) . '</h2>';
            $items = $mediaByChapter[$n] ?? [];
            if ($items === []) {
                $html .= '<p>No extra media for this chapter yet.</p>';
                continue;
            }
            foreach ($items as $figureIndex => $item) {
                $html .= '<figure>';
                if (isset($item['svg'])) {
                    $html .= $item['svg'];
                } elseif (isset($item['table']['columns'], $item['table']['rows'])) {
                    $html .= '<div class="overflow"><table><thead><tr>';
                    foreach ($item['table']['columns'] as $column) {
                        $html .= '<th>' . $e((string) $column) . '</th>';
                    }
                    $html .= '</tr></thead><tbody>';
                    foreach ($item['table']['rows'] as $row) {
                        $html .= '<tr>';
                        foreach ($row as $cell) {
                            $html .= '<td>' . $e((string) $cell) . '</td>';
                        }
                        $html .= '</tr>';
                    }
                    $html .= '</tbody></table></div>';
                }
                $html .= '<figcaption>Figure ' . $n . '.' . ($figureIndex + 1) . ' — ' . $e((string) ($item['title'] ?? '')) . '. ' . $e((string) ($item['caption'] ?? '')) . '</figcaption>';
                if (isset($item['ai']['prompt'])) {
                    $html .= '<div class="prompt"><b>The image for this spot is generated from:</b> ' . $e((string) $item['ai']['prompt']) . '</div>';
                }
                $html .= '</figure>';
            }
            $html .= '<p style="font-size:.85em;color:#5a6070">🎧 Audiobook chapter: published here when the author uploads the audio (see bin/synthesize-audiobook.php).</p>';
        }
        $html .= '<p style="margin-top:3em;font-size:.8em;color:#5a6070">Companion page for the print edition · base address: ' . $e($baseUrl) . '</p>';
        return $html . '</main></body></html>';
    }

    /** A printable sheet of QR cards for the book interior or back matter. */
    public function exportQrSheetHtml(array $plan, array $metadata): string
    {
        $e = static fn (string $v): string => htmlspecialchars($v, ENT_QUOTES, 'UTF-8');
        $title = trim((string) ($metadata['title'] ?? 'Untitled')) ?: 'Untitled';
        $html = '<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><title>' . $e($title) . ' — QR Sheet</title><style>'
            . 'body{font-family:Georgia,serif;color:#000;margin:1in .75in}'
            . 'h1{text-align:center}p.lead{text-align:center;font-size:.9em}'
            . '.grid{display:flex;flex-wrap:wrap;gap:18px;justify-content:center}'
            . '.card{width:180px;border:1px solid #999;border-radius:8px;padding:10px;text-align:center;page-break-inside:avoid}'
            . '.card b{display:block;font-size:.8em;margin-bottom:6px}.card small{display:block;font-size:.6em;word-break:break-all;color:#444;margin-top:6px}'
            . '</style></head><body><h1>' . $e($title) . '</h1>'
            . '<p class="lead">Scan any code with a phone camera to open that chapter\'s media — audio, images, and figures.</p><div class="grid">';
        $html .= '<div class="card"><b>' . $e((string) $plan['master']['label']) . '</b>' . $plan['master']['qr_svg'] . '<small>' . $e((string) $plan['master']['url']) . '</small></div>';
        foreach ((array) $plan['chapters'] as $entry) {
            $html .= '<div class="card"><b>Ch. ' . (int) $entry['chapter'] . ': ' . $e((string) $entry['title']) . '</b>'
                . $entry['qr_svg'] . '<small>' . $e((string) $entry['url']) . '</small></div>';
        }
        return $html . '</div></body></html>';
    }

    public function normalizeBaseUrl(string $baseUrl): string
    {
        $baseUrl = trim($baseUrl);
        if ($baseUrl === '' || !preg_match('~^https?://~i', $baseUrl)) {
            return self::DEFAULT_BASE_URL;
        }
        return rtrim($baseUrl, '/#');
    }
}
