<?php

declare(strict_types=1);

/**
 * Set (or change) the QueryBook Translate admin password.
 *   php translate/admin/set-password.php            prompts for the password
 *   php translate/admin/set-password.php 'secret'   non-interactive
 * Writes admin/admin-config.php (git-ignored) containing only a password hash.
 */

if (PHP_SAPI !== 'cli') {
    http_response_code(404);
    exit;
}

$password = $argv[1] ?? null;
if ($password === null) {
    fwrite(STDOUT, 'New admin password: ');
    if (DIRECTORY_SEPARATOR === '/') {
        shell_exec('stty -echo');
    }
    $password = rtrim((string) fgets(STDIN), "\r\n");
    if (DIRECTORY_SEPARATOR === '/') {
        shell_exec('stty echo');
    }
    fwrite(STDOUT, "\n");
}
if (strlen($password) < 10) {
    fwrite(STDERR, "Use at least 10 characters.\n");
    exit(1);
}

$file = __DIR__ . '/admin-config.php';
$body = "<?php\n\n// Generated by set-password.php — keep out of version control.\nreturn ['password_hash' => " . var_export(password_hash($password, PASSWORD_DEFAULT), true) . "];\n";
file_put_contents($file, $body, LOCK_EX);
@chmod($file, 0600);
fwrite(STDOUT, "Admin password saved to {$file}\n");
