# Brief additions: QueryBook support for external agent-wrapper services (FIG. 56). Each paragraph: list of (text, bold).
SUMMARY_G = [[("   g. Support for external agent-wrapper services — Verified Agent Transport and similar relays that check an AI agent's messages and actions in transit — through a read-only claim verification interface, reserved frame extensions, append access to the security record, a session certificate type, and Agent Gateway and tool-server hooks (FIG. 56). The wrapper services themselves are described separately.", False)]]

SYSTEM_7 = [[("7. Support for agent-wrapper services. Services that sit beside an AI agent and check what it says and does — Verified Agent Transport is one — can use QueryBook to check facts, record results and issue session certificates, without ever writing to the knowledge store. See FIG. 56.", False)]]

CORE = [
 [("10. Support interfaces for agent-wrapper services (FIG. 56). ", True),
  ("An external agent-wrapper service (5690), such as Verified Agent Transport, sits between an AI agent (5695) and its destination (5697) and calls QueryBook support interfaces (5600) under a registered identity. Verification interfaces (5610) comprise a read-only claim verification endpoint (5612) that returns verified, contradicted or unknown with a citation; a contradiction query template (5614) matching the same subject and predicate with a conflicting value; a fingerprint-only mode (5616) in which claim text never leaves the caller; and triple extraction with assertion-type labels (5618) distinguishing fact from opinion, plan and prediction. Transport interfaces (5620) reserve frame message types 16–31 for extensions (5622), reserve a header flag and define the reserved field as a session number and hop count (5624), and add a Python frame codec with QUIC lanes and TLS fallback (5626) and have/want fingerprint reconciliation (5628). Record and certificate interfaces (5630) sign verdicts with a published key (5632), accept appends from registered services to the security log (5634), compute a Merkle root and proofs over one session's entries (5636), and provide a third-party session certificate type (5638). Governance interfaces (5640) register wrapper services (5642), export signed policy bundles (5644), expose pre-call and post-call hooks and a hash of each tool result record in the tool server (5646), and keep an evidence pair per agent as a reputation (5648). These interfaces rest on the Fact Unit store and FQL (5650), the security log (5660), certificates (5670), the Agent Gateway and MCP server (5680) and the framed hybrid transport (5685). Verification is read-only and records are append-only: a wrapper service never writes Fact Units.", False)],
 [("11. Status. ", True),
  ("The support interfaces of FIG. 56 are specified in this application and are not yet implemented; no performance figures are asserted for them.", False)],
]

ARCH = [[("Referring to FIG. 56: the support interfaces extend the governance domain's boundary services. An external agent-wrapper service is a registered caller of the system, never a domain of it; it reads through the verification interfaces and appends to the security record under its own identity.", False)]]

BRIEF = [[("FIG. 56 ", True), ("is a block diagram of the support interfaces QueryBook provides to external agent-wrapper services such as Verified Agent Transport, grouped as verification, transport, record and certificate, and governance interfaces over the Fact Unit store, security log, certificates, Agent Gateway and MCP server, and framed hybrid transport.", False)]]
NOTE = [[("[Drafting note: FIG. 56 is added to the drawing set, which now comprises FIG. 1–56, one figure per sheet.]", False)]]

CLAIMS = [
 ("355.  ", "The method of claim 1, further comprising providing, to an external service interposed between an artificial-intelligence agent and a network, a read-only verification interface that receives a candidate knowledge record or its semantic fingerprint and returns a signed verdict of verified, contradicted or unknown, said verdict being determined by fingerprint lookup among certified records and, absent a match, by a query for certified records having the same subject and predicate and a conflicting value."),
 ("356.  ", "The method of claim 355, further comprising reserving a range of frame message types and a header flag of the framed transport for said external service, and accepting from said service, under a registered identity, appends to the hash-chained security record, from which a Merkle root over the entries of one session is computed and sealed as a session certificate verifiable by any party."),
 ("357.  ", "The method of claim 355, wherein said external service is registered through the agent gateway with read-only verification rights and append-only record rights, receives signed policy bundles, and observes tool calls and hashed tool result records through hooks of the tool server, and wherein said service is never permitted to write knowledge records."),
]
CLAIM_NOTE = "[Drafting note: claims 355–357 are added for support of external agent-wrapper services (FIG. 56); the claim count in the Claim Set heading is to be read as 357.]"
