# Additions for Verified Agent Transport (VAT). Each paragraph: list of (text, bold).
SUMMARY_G = [[("   g. Verified Agent Transport, a wrapper service carried inside the framed hybrid transport of FIG. 55, in which every message an AI agent sends or receives is a typed frame whose factual claims are expressed as Fact Units, verified in transit against the Fact Unit store and by an FQL contradiction query, answered with a signed verdict on a separate control lane, recorded in a hash-chained ledger, and summarized in a session certificate (FIG. 56–57). This feature is specified in this application and is not yet reduced to practice.", False)]]

SYSTEM_7 = [[("7. Honest agent traffic. An AI agent is placed behind a sidecar that is its only route to the network. Each factual statement the agent sends is checked against certified Fact Units before it arrives, contradicted statements are blocked or labelled, each action is compared with the intent the agent declared, and each session ends with a certificate anyone can check. See FIG. 56 and FIG. 57.", False)]]

CORE = [
 [("10. Verified Agent Transport — deployment (FIG. 56). ", True),
  ("An AI agent (5600) runs inside an egress-lock boundary (5605) — a network policy, firewall rule set or container network namespace — that permits outbound connections only to a sidecar (5610) co-located with the agent. The sidecar comprises protocol adapters (5612) that accept the agent's existing traffic, including Model Context Protocol tool calls, agent-to-agent messages and HTTP requests; a claim extractor (5614); an intent binder (5616); and a frame codec and signer (5618) that emits frames of the format of FIG. 55. Frames travel over one encrypted connection (5620) to a peer sidecar (5630) that delivers them to the destination (5640), which may be a tool, a data source or another agent.", False)],
 [("11. Lanes and frame types. ", True),
  ("The encrypted connection carries three lanes: a control lane (5622) for verdicts, certificates and acknowledgements; a normal lane (5624) for claims, queries, answers, intents, actions and results; and a bulk lane (5626) for data and media. Over QUIC each lane is an independent stream so that a stalled bulk transfer does not delay a verdict; where QUIC is unavailable the lanes are carried over TLS on TCP as separate connections. The frame header of FIG. 55 is unchanged; new message types identify claim, query, answer, intent, action, result, verdict, data, certificate, have, want and free-text frames, a flag marks a frame that has passed a verifying hop, and the reserved header field carries a session number and hop count.", False)],
 [("12. Claim verification (FIG. 57). ", True),
  ("An outbound message (5700) is classified (5705) into factual statements and non-factual content; non-factual content is labelled as such and forwarded (5706). Each factual statement is extracted and normalized into a candidate Fact Unit and fingerprinted (5710). The UFCS verification service (5650) first looks up the fingerprint among certified Fact Units (5720); if no exact match exists it runs an FQL contradiction query (5725) for certified units with the same subject and predicate and a conflicting value. The outcome is VERIFIED (5731), CONTRADICTED (5732) or UNKNOWN (5733). The service returns a signed VERDICT frame (5740) on the control lane, carrying the fingerprints and confidence of the units relied on, and the sidecar applies policy: forward, annotate, hold for review, or block.", False)],
 [("13. Intent binding. ", True),
  ("Before acting, the agent declares an intent frame naming the tool, target and purpose. Each subsequent action frame is compared with the declared intent, and each result the agent reports is compared with the record returned by the tool itself (5745). A mismatch produces a CONTRADICTED verdict without reference to the Fact Unit store, so that an agent cannot misreport what it did or what a tool returned.", False)],
 [("14. Ledger, certificate and reputation. ", True),
  ("Every claim, verdict, intent, action and result is appended to a hash-chained ledger (5660, 5750). At the end of a session the sidecar issues an Agent Session Certificate (5770) stating the number of verified, contradicted and unknown claims, the coverage — the share of factual statements that were checked — and a Merkle root over the ledger entries, signed by the verification service. The certificate is itself sealed as a Fact Unit and may be checked by any party with the certificate of FIG. 51, and may optionally be anchored to a public ledger. Each agent's history accumulates as an evidence pair of verified and contradicted counts (5780), the same Beta model used for Fact Unit confidence (FIG. 19); a control plane (5670) restricts or isolates an agent whose reputation falls below a threshold.", False)],
 [("15. Have/want exchange and privacy mode. ", True),
  ("Before bulk transfer, peers exchange have and want frames listing the fingerprints each holds or needs, using a Bloom filter when a list exceeds 4,096 fingerprints, so that only missing Fact Units are sent (5790). In privacy mode (5795) the sidecar sends only fingerprints and verdicts are computed from fingerprints alone, so that message content is not disclosed to the verification service.", False)],
 [("16. Status. ", True),
  ("Verified Agent Transport is specified in this application and in the accompanying technical specification; it has not yet been reduced to practice, and no performance figures are asserted for it. It reuses the frame format, Fact Unit store, FQL engine, certificate and Agent Gateway already described.", False)],
]

ARCH = [[("Referring to FIG. 56 and FIG. 57: Verified Agent Transport operates at the boundary governed by the governance domain, alongside the Agent Gateway. The sidecar (5610) is a caller of the system, not a domain of it; the verification service (5650) is a read-only client of the Fact Unit store and FQL engine; and the ledger and certificates (5660) are written as Fact Units under the same provenance and integrity rules as every other record.", False)]]

BRIEF = [
 [("FIG. 56 ", True), ("is a block diagram of Verified Agent Transport, showing an AI agent inside an egress-lock boundary, a sidecar comprising protocol adapters, claim extraction, intent binding and a frame codec and signer, an encrypted connection carrying control, normal and bulk lanes to a peer sidecar and destination, a UFCS verification service, a ledger and certificate store, and a control plane.", False)],
 [("FIG. 57 ", True), ("is a flow diagram of claim verification in Verified Agent Transport, showing classification of an outbound message, extraction and fingerprinting of factual statements, fingerprint lookup and FQL contradiction query, the verified, contradicted and unknown outcomes, the signed verdict and policy, intent and result binding, ledger append, the session certificate, reputation, have/want exchange and privacy mode.", False)],
]
NOTE = [[("[Drafting note: FIG. 56–57 are added to the drawing set, which now comprises FIG. 1–57, one figure per sheet.]", False)]]

CLAIMS = [
 ("355.  ", "A method of verifying communications of an artificial-intelligence agent, comprising: receiving, at a relay interposed between the agent and a network, a message sent by the agent; encoding the message as one or more frames each having a header that identifies a message type, at least one frame carrying a factual statement expressed as a Fact Unit having a content fingerprint; determining, at a verification service, a verdict for the Fact Unit by looking up said fingerprint among certified Fact Units and, absent a match, executing a query for certified Fact Units having the same subject and predicate and a conflicting value; transmitting a signed verdict frame on a control lane separate from the lane carrying the message; appending the frame and the verdict to a hash-chained record; and issuing, at the end of a session, a session certificate stating counts of verdicts and a Merkle root over the hash-chained record."),
 ("356.  ", "The method of claim 355, wherein a message containing a Fact Unit whose verdict is contradicted is blocked, held for review, or forwarded with an annotation identifying the certified Fact Units that contradict it."),
 ("357.  ", "The method of claim 355, further comprising receiving from the agent an intent frame declaring a tool, a target and a purpose; comparing each subsequent action frame with the declared intent; comparing each result reported by the agent with a record returned by the tool; and issuing a contradicted verdict upon a mismatch."),
 ("358.  ", "The method of claim 355, further comprising exchanging between relays have and want frames identifying fingerprints held and needed, represented as a Bloom filter when their number exceeds a threshold, and transmitting only Fact Units identified as needed."),
 ("359.  ", "The method of claim 355, wherein in a privacy mode the relay transmits fingerprints without message content and the verdict is determined from the fingerprints alone."),
 ("360.  ", "The method of claim 355, wherein the control lane, a normal lane and a bulk lane are carried as independent streams of a QUIC connection, and, where QUIC is unavailable, as separate connections over TLS on TCP."),
 ("361.  ", "The method of claim 355, wherein the relay is a sidecar co-located with the agent, outbound network access of the agent is restricted by an egress rule to the sidecar, and the sidecar translates Model Context Protocol, agent-to-agent and HTTP traffic into said frames."),
 ("362.  ", "The method of claim 355, wherein the session certificate further states a coverage measure equal to the share of factual statements in the session that were verified or contradicted, statements not checked being reported as unchecked."),
 ("363.  ", "The method of claim 355, further comprising maintaining for the agent an evidence pair of verified and contradicted counts, computing a reputation from said pair, and restricting or isolating the agent when the reputation falls below a threshold."),
 ("364.  ", "The method of claim 355, wherein the session certificate is sealed as a Fact Unit, is optionally anchored to a public ledger, and is verifiable by a party holding neither the agent nor the verification service."),
 ("365.  ", "A non-transitory computer-readable medium storing instructions that, when executed by one or more processors, cause the processors to perform the method of any one of claims 355 to 364."),
]
CLAIM_NOTE = "[Drafting note: claims 355–365 are added for Verified Agent Transport (FIG. 56–57); the claim count in the Claim Set heading is to be read as 365.]"
